/**
 * Copies occt-import-js (OpenCascade in WebAssembly, LGPL-2.1) into `occt/` for the STEP
 * worker: the WebAssembly module, its Emscripten glue as an ES module, and the licences.
 */
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const out = fileURLToPath(new URL('../occt/', import.meta.url));
const dist = dirname(fileURLToPath(import.meta.resolve('occt-import-js')));
const { version } = JSON.parse(readFileSync(join(dist, '../package.json'), 'utf8'));

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
copyFileSync(join(dist, 'occt-import-js.wasm'), join(out, 'occt-import-js.wasm'));
copyFileSync(join(dist, 'license.occt-import-js.txt'), join(out, 'LICENSE.occt-import-js.txt'));
copyFileSync(join(dist, 'license.occt.txt'), join(out, 'LICENSE.occt.txt'));
// The glue is a script that assigns `occtimportjs`; its Node.js branch calls `require`, which
// the stub keeps bundlers from resolving (the worker never runs in Node.js).
const glue = readFileSync(join(dist, 'occt-import-js.js'), 'utf8');
writeFileSync(
  join(out, 'occt-import-js.mjs'),
  `// occt-import-js ${version} (LGPL-2.1, see LICENSE.occt-import-js.txt and LICENSE.occt.txt),
// its Emscripten glue as an ES module. Generated by @boardui/models (scripts/occt.mjs).
const require = (name) => {
  throw new Error(\`\${name} is not available\`);
};
${glue}
export default occtimportjs;
`,
);
writeFileSync(
  join(out, 'occt-import-js.d.mts'),
  `/** occt-import-js's module factory. */
declare const occtimportjs: (options?: {
  locateFile?: (path: string) => string;
}) => Promise<{
  ReadStepFile(content: Uint8Array, params: Record<string, unknown> | null): unknown;
}>;
export default occtimportjs;
`,
);
console.log(`occt/: occt-import-js ${version}`);
