import {
  Location,
  Set,
  AssemblyDrawing,
  CadData,
  Circle,
  Color,
  ColorRef,
  Component,
  Content,
  Contour,
  Dictionary,
  DictionaryEntry,
  Ecad,
  Features,
  FillDesc,
  FillDescRef,
  Hole,
  Layer,
  LayerFeature,
  LayerRef,
  LineDesc,
  LineDescRef,
  Marking,
  NonstandardAttribute,
  Outline,
  Package,
  Pad,
  Pin,
  PinRef,
  PolyBegin,
  Polygon,
  Polyline,
  PolyStepCurve,
  PolyStepSegment,
  RectCenter,
  Span,
  StandardPrimitiveRef,
  Step,
  StepRef,
  XForm,
  IPC2581,
  FunctionMode,
  SilkScreen,
  Bom,
  BomHeader,
  BomItem,
  BomRef,
  Characteristics,
  Enumerated,
  Measured,
  Ranged,
  RefDes,
  Textual,
  Oval,
  Line,
} from './ipc';
import { XMLtoJSMapping } from './xml-to-js-mapping';

const defaultIPCMappings = new Array<XMLtoJSMapping>(
  ['Bom', Bom.prototype, ['bom']],
  ['BomItem', BomItem.prototype, ['bomItems']],
  ['BomHeader', BomHeader.prototype, ['bomHeader']],
  ['BomRef', BomRef.prototype, ['bomRefs']],
  ['CadData', CadData.prototype, ['cadData']],
  ['Content', Content.prototype, ['content']],
  ['Contour', Contour.prototype, ['content', 'features']],
  ['Cutout', Polygon.prototype, ['cutouts']],
  ['Ecad', Ecad.prototype, ['ecad']],
  ['EntryLineDesc', DictionaryEntry.prototype, ['entries']],
  ['Features', Features.prototype, ['features']],
  ['IPC-2581', IPC2581.prototype, []],
  ['Layer', Layer.prototype, ['layers']],
  ['LayerFeature', LayerFeature.prototype, ['layerFeatures']],
  ['LayerRef', LayerRef.prototype, ['layerRefs']],
  ['Step', Step.prototype, ['steps']],
  ['Profile', Contour.prototype, ['profile']],
  ['Polygon', Polygon.prototype, ['polygon']],
  ['PolyBegin', PolyBegin.prototype, ['polyBegin']],
  ['PolyStepSegment', PolyStepSegment.prototype, ['polySteps']],
  ['PolyStepCurve', PolyStepCurve.prototype, ['polySteps']],
  ['Set', Set.prototype, ['sets']],
  ['ColorRef', ColorRef.prototype, ['colorGroups']],
  ['DictionaryColor', Dictionary.prototype, ['dictionaryColor']],
  ['EntryColor', DictionaryEntry.prototype, ['entries']],
  ['Color', Color.prototype, ['content']],
  ['DictionaryLineDesc', Dictionary.prototype, ['dictionaryLineDesc']],
  ['LineDesc', LineDesc.prototype, ['content', 'lineDesc']],
  ['LineDescRef', LineDescRef.prototype, ['lineDesc']],
  ['Polyline', Polyline.prototype, ['features', 'polyline']],
  ['Package', Package.prototype, ['packages']],
  ['Outline', Outline.prototype, ['outline']],
  ['Pin', Pin.prototype, ['pins']],
  ['Location', Location.prototype, ['location']],
  [
    'StandardPrimitiveRef',
    StandardPrimitiveRef.prototype,
    ['standardPrimitiveRef', 'feature'],
  ],
  ['AssemblyDrawing', AssemblyDrawing.prototype, ['assemblyDrawing']],
  ['Marking', Marking.prototype, ['marking']],
  ['DictionaryUser', Dictionary.prototype, ['dictionaryStandard']],
  ['EntryUser', DictionaryEntry.prototype, ['entries']],
  ['DictionaryStandard', Dictionary.prototype, ['dictionaryStandard']],
  ['EntryStandard', DictionaryEntry.prototype, ['entries']],
  ['DictionaryFillDesc', Dictionary.prototype, ['dictionaryFillDesc']],
  ['EntryFillDesc', DictionaryEntry.prototype, ['entries']],
  ['FillDesc', FillDesc.prototype, ['content', 'fillDesc']],
  ['FillDescRef', FillDescRef.prototype, ['fillDesc']],
  ['Circle', Circle.prototype, ['content']],
  ['Oval', Oval.prototype, ['content']],
  ['RectCenter', RectCenter.prototype, ['content']],
  ['Component', Component.prototype, ['components']],
  ['Xform', XForm.prototype, ['xform']],
  ['Hole', Hole.prototype, ['holes']],
  ['StepRef', StepRef.prototype, ['stepRefs']],
  ['Span', Span.prototype, ['span']],
  ['Pad', Pad.prototype, ['pads']],
  [
    'NonstandardAttribute',
    NonstandardAttribute.prototype,
    ['nonstandardAttributes'],
  ],
  ['PinRef', PinRef.prototype, ['pinRefs']],
  ['SilkScreen', SilkScreen.prototype, ['silkScreen']],
  ['Measured', Measured.prototype, ['measured']],
  ['Ranged', Ranged.prototype, ['ranged']],
  ['Enumerated', Enumerated.prototype, ['enumerated']],
  ['Textual', Textual.prototype, ['textual']],
  ['RefDes', RefDes.prototype, ['refDes']],
  ['Characteristics', Characteristics.prototype, ['characteristics']],
  ['FunctionMode', FunctionMode.prototype, ['functionMode']],
  ['Line', Line.prototype, ['features']]
);

export const DefaultIPCMappings = defaultIPCMappings;
