#!/usr/bin/env python3
"""Writes the hand-written samples (spec/samples/README.md).

Each sample is a minimal IPC-2581 rev C file for one spec rule. Run from any directory:

    python3 spec/samples/hand-written/generate.py

The script only uses the standard library. Coordinates are written in millimetres here and
converted to each file's units.
"""

import base64
import json
import math
import struct
from pathlib import Path

HERE = Path(__file__).resolve().parent
UNITS = {"MILLIMETER": 1.0, "INCH": 1 / 25.4, "MICRON": 1000.0}


class Doc:
    """An IPC-2581 document in one unit system."""

    def __init__(self, units="MILLIMETER", mode="FABRICATION"):
        self.units = units
        self.mode = mode
        self.lines = {}
        self.standard = {}
        self.layers = []
        self.step = []
        self.colors = {}
        self.specs = []
        # Steps written before the main step: (name, datum, elements).
        self.steps = []
        self.step_refs = None

    def u(self, mm):
        """A length in mm, formatted in the document's units."""
        v = mm * UNITS[self.units]
        return f"{v:.10g}"

    def xy(self, x, y, prefix=""):
        return f'{prefix}x="{self.u(x)}" {prefix}y="{self.u(y)}"'

    def line_desc(self, name, width, end="ROUND", prop=None):
        prop = f' lineProperty="{prop}"' if prop else ""
        self.lines[name] = f'<LineDesc lineWidth="{self.u(width)}" lineEnd="{end}"{prop}/>'

    def primitive(self, name, xml):
        self.standard[name] = xml

    def color(self, name, r, g, b):
        self.colors[name] = f'<Color r="{r}" g="{g}" b="{b}"/>'

    def spec(self, name, xml):
        self.specs.append(f'<Spec name="{name}">{xml}</Spec>')

    def layer(self, name, function, side, span=None, specs=()):
        inner = "".join(f'<SpecRef id="{s}"/>' for s in specs)
        inner += f'<Span fromLayer="{span[0]}" toLayer="{span[1]}"/>' if span else ""
        self.layers.append(
            f'<Layer name="{name}" layerFunction="{function}" side="{side}">{inner}</Layer>'
        )

    def polygon(self, points, close=True):
        (x0, y0), rest = points[0], points[1:]
        steps = "".join(f"<PolyStepSegment {self.xy(x, y)}/>" for x, y in rest)
        if close:
            steps += f"<PolyStepSegment {self.xy(x0, y0)}/>"
        return f"<PolyBegin {self.xy(x0, y0)}/>{steps}"

    def rect(self, x0, y0, x1, y1):
        return self.polygon([(x0, y0), (x1, y0), (x1, y1), (x0, y1)])

    def add_step(self, name, datum, elements):
        self.steps.append((name, datum, elements))

    def write(self, path, name, step_name="board"):
        dict_units = f'units="{self.units}"'
        lines = "".join(
            f'<EntryLineDesc id="{k}">{v}</EntryLineDesc>' for k, v in self.lines.items()
        )
        standard = "".join(
            f'<EntryStandard id="{k}">{v}</EntryStandard>' for k, v in self.standard.items()
        )
        colors = "".join(f'<EntryColor id="{k}">{v}</EntryColor>' for k, v in self.colors.items())
        colors = f"\n    <DictionaryColor>{colors}</DictionaryColor>" if colors else ""
        header = f'<CadHeader units="{self.units}"/>'
        if self.specs:
            specs = "".join(f"\n      {s}" for s in self.specs)
            header = f'<CadHeader units="{self.units}">{specs}\n    </CadHeader>'
        step_refs = "".join(
            f'\n    <StepRef name="{s}"/>' for s in (self.step_refs or [step_name])
        )
        steps = "".join(
            f'\n      <Step name="{s}">\n        <Datum {self.xy(*datum)}/>'
            + "".join(f"\n        {e}" for e in elements)
            + "\n      </Step>"
            for s, datum, elements in self.steps
        )
        xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {name}: hand-written boardui sample, generated by generate.py. -->
<IPC-2581 revision="C" xmlns="http://webstds.ipc.org/2581">
  <Content>
    <FunctionMode mode="{self.mode}"/>{step_refs}
    <DictionaryLineDesc {dict_units}>{lines}</DictionaryLineDesc>
    <DictionaryStandard {dict_units}>{standard}</DictionaryStandard>{colors}
  </Content>
  <Ecad name="{name}">
    {header}
    <CadData>
      {chr(10).join("      " + l for l in self.layers).strip()}{steps}
      <Step name="{step_name}">
        <Datum x="0" y="0"/>
{chr(10).join("        " + s for s in self.step)}
      </Step>
    </CadData>
  </Ecad>
</IPC-2581>
"""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(xml)


def two_layers(d, drill=True):
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("BOTTOM", "CONDUCTOR", "BOTTOM")
    if drill:
        d.layer("DRILL", "DRILL", "ALL", span=("TOP", "BOTTOM"))


def profile(d, w, h):
    d.step.append(f"<Profile><Polygon>{d.rect(0, 0, w, h)}</Polygon></Profile>")


def pad(d, x, y, shape, pin=None, rotation=None):
    xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
    pin_ref = f'<PinRef componentRef="{pin[0]}" pin="{pin[1]}"/>' if pin else ""
    return (
        f"<Pad>{xform}<Location {d.xy(x, y)}/>"
        f'<StandardPrimitiveRef id="{shape}"/>{pin_ref}</Pad>'
    )


def trace(d, points, line):
    return (
        f'<Features><Location x="0" y="0"/><Polyline>{d.polygon(points, close=False)}'
        f'<LineDescRef id="{line}"/></Polyline></Features>'
    )


def fill(d, x0, y0, x1, y1):
    return (
        f'<Features><Location x="0" y="0"/><Contour><Polygon>{d.rect(x0, y0, x1, y1)}'
        f"</Polygon></Contour></Features>"
    )


def minimal(units):
    """One resistor, two pads, one trace, one via (spec §4–§8)."""
    d = Doc(units)
    d.line_desc("TRACE", 0.25)
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.0)}"/>')
    d.primitive("VIA", f'<Circle diameter="{d.u(0.6)}"/>')
    two_layers(d)
    profile(d, 10, 6)
    d.step.append(
        f'<Package name="R0603" type="RESISTOR" pinOne="1" height="{d.u(0.5)}">'
        f'<Outline><Polygon>{d.rect(-1.2, -0.6, 1.2, 0.6)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(-0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f'<Pin number="2"><Location {d.xy(0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f"</Package>"
    )
    d.step.append(
        f'<Component refDes="R1" packageRef="R0603" layerRef="TOP" part="RES-10K" '
        f'mountType="SMT" standoff="0" height="{d.u(0.5)}"><Location {d.xy(3, 3)}/></Component>'
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="N1" padUsage="TERMINATION">{pad(d, 2.2, 3, "PAD", ("R1", "1"))}</Set>'
        f'<Set net="N2" padUsage="TERMINATION">{pad(d, 3.8, 3, "PAD", ("R1", "2"))}</Set>'
        f'<Set net="N2">{trace(d, [(3.8, 3), (7, 3)], "TRACE")}</Set>'
        f'<Set net="N2" padUsage="VIA">{pad(d, 7, 3, "VIA")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="BOTTOM">'
        f'<Set net="N2" padUsage="VIA">{pad(d, 7, 3, "VIA")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set net="N2">'
        f'<Hole name="H1" diameter="{d.u(0.3)}" platingStatus="VIA" plusTol="0" minusTol="0" {d.xy(7, 3)}/>'
        "</Set></LayerFeature>"
    )
    return d


def overlap_priority():
    """Pad over trace over plane, and ties in document order (spec §6.2)."""
    d = Doc()
    d.line_desc("WIDE", 0.5)
    d.line_desc("THIN", 0.3)
    d.primitive("PAD", f'<Circle diameter="{d.u(1.2)}"/>')
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 10, 4)
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        # 0: a plane, the lowest priority.
        f'<Set net="GND">{fill(d, 0, 0, 8, 4)}</Set>'
        # 1: a trace across the plane.
        f'<Set net="SIG">{trace(d, [(1, 2), (7, 2)], "WIDE")}</Set>'
        # 2: a pad on the trace.
        f'<Set net="SIG" padUsage="TERMINATION">{pad(d, 4, 2, "PAD")}</Set>'
        # 3: a second plane overlapping the first: the earlier one keeps the overlap.
        f'<Set net="GND">{fill(d, 6, 1, 10, 3)}</Set>'
        # 4: a second trace crossing the first: the earlier one keeps the crossing.
        f'<Set net="SIG2">{trace(d, [(2, 3.5), (2, 0.5)], "THIN")}</Set>'
        "</LayerFeature>"
    )
    return d


def negative_polarity():
    """A plane with negative cut-outs; later features are not cut (spec §6.2)."""
    d = Doc()
    d.line_desc("TRACE", 0.3)
    d.primitive("HOLE", f'<Circle diameter="{d.u(1.5)}"/>')
    d.primitive("SLOT", f'<RectCenter width="{d.u(1.0)}" height="{d.u(3.0)}"/>')
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 8, 4)
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND">{fill(d, 0, 0, 8, 4)}</Set>'
        f'<Set polarity="NEGATIVE"><Features><Location {d.xy(2, 2)}/><StandardPrimitiveRef id="HOLE"/></Features></Set>'
        f'<Set polarity="NEGATIVE"><Features><Location {d.xy(6, 2)}/><StandardPrimitiveRef id="SLOT"/></Features></Set>'
        f'<Set net="SIG">{trace(d, [(1, 2), (7, 2)], "TRACE")}</Set>'
        "</LayerFeature>"
    )
    return d


def zero_width_lines():
    """Silkscreen strokes with zero-width lines are 0.1 mm hairlines (spec §6.1)."""
    d = Doc()
    d.line_desc("ZERO", 0)
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("SILK", "SILKSCREEN", "TOP")
    profile(d, 6, 4)
    line = (
        f'<Line startX="{d.u(1)}" startY="{d.u(3)}" endX="{d.u(3)}" endY="{d.u(3)}">'
        '<LineDescRef id="ZERO"/></Line>'
    )
    d.step.append(
        '<LayerFeature layerRef="SILK">'
        f'<Set>{trace(d, [(1, 1), (5, 1), (5, 3)], "ZERO")}</Set>'
        f'<Set><Features><Location x="0" y="0"/>{line}</Features></Set>'
        "</LayerFeature>"
    )
    return d


def fiducials():
    """The four fiducial elements are copper features of kind FIDUCIAL (spec §6.2, §8.2)."""
    d = Doc()
    d.primitive("FID", f'<Circle diameter="{d.u(1.0)}"/>')
    two_layers(d, drill=False)
    profile(d, 12, 8)

    def fiducial(element, x, y, shape, rotation=None):
        xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
        return f"<{element}>{xform}<Location {d.xy(x, y)}/>{shape}</{element}>"

    d.step.append(
        '<LayerFeature layerRef="TOP"><Set>'
        + fiducial("GlobalFiducial", 1.5, 1.5, '<StandardPrimitiveRef id="FID"/>')
        + fiducial("GlobalFiducial", 10.5, 6.5, '<StandardPrimitiveRef id="FID"/>')
        + fiducial("LocalFiducial", 4, 4, f'<Circle diameter="{d.u(0.6)}"/>')
        + fiducial("BadBoardMark", 8, 4, f'<Circle diameter="{d.u(1.5)}"/>')
        + fiducial(
            "GoodPanelMark",
            10.5,
            1.5,
            f'<RectCenter width="{d.u(1.0)}" height="{d.u(1.0)}"/>',
            rotation=45,
        )
        + "</Set></LayerFeature>"
    )
    return d


def hexagon_moire():
    """Hexagon (corner up, `length` across corners) and Moire primitives (spec §6.1)."""
    d = Doc()
    d.line_desc("THIN", 0.15)
    d.primitive("HEX", f'<Hexagon length="{d.u(2.0)}"/>')
    d.primitive(
        "HEX_HOLLOW",
        f'<Hexagon length="{d.u(2.0)}"><LineDescRef id="THIN"/>'
        '<FillDesc fillProperty="HOLLOW"/></Hexagon>',
    )
    d.primitive(
        "MOIRE",
        f'<Moire diameter="{d.u(4.0)}" ringWidth="{d.u(0.2)}" ringGap="{d.u(0.6)}" '
        f'ringNumber="3" lineWidth="{d.u(0.15)}" lineLength="{d.u(5.0)}" lineAngle="0"/>',
    )
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 14, 6)

    def feature(x, y, shape, rotation=None):
        xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
        return (
            f"<Set><Features>{xform}<Location {d.xy(x, y)}/>"
            f'<StandardPrimitiveRef id="{shape}"/></Features></Set>'
        )

    d.step.append(
        '<LayerFeature layerRef="TOP">'
        + feature(2, 3, "HEX")
        + feature(5, 3, "HEX", rotation=30)
        + feature(8, 3, "HEX_HOLLOW")
        + feature(11.5, 3, "MOIRE")
        + "</LayerFeature>"
    )
    return d


def hatch_fill():
    """HATCH and MESH fills are lines clipped to the area, plus the outline (spec §6.1)."""
    d = Doc()
    d.line_desc("EDGE", 0.3)
    d.primitive(
        "MESHED",
        f'<Circle diameter="{d.u(5.0)}"><FillDesc fillProperty="MESH" lineWidth="{d.u(0.2)}" '
        f'pitch1="{d.u(0.8)}" angle1="0" pitch2="{d.u(0.8)}" angle2="90"/></Circle>',
    )
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 16, 7)
    hatched = (
        f"<Polygon>{d.polygon([(1, 1), (8, 1), (8, 6), (4, 6), (1, 3)])}"
        '<LineDescRef id="EDGE"/>'
        f'<FillDesc fillProperty="HATCH" lineWidth="{d.u(0.2)}" pitch1="{d.u(0.7)}" angle1="45"/>'
        "</Polygon>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND"><Features><Location x="0" y="0"/>{hatched}</Features></Set>'
        f'<Set net="GND"><Features><Location {d.xy(12, 3.5)}/>'
        '<StandardPrimitiveRef id="MESHED"/></Features></Set>'
        "</LayerFeature>"
    )
    return d


def line_styles():
    """lineProperty patterns along lines, arcs and outlines, and an ERASE line (spec §6.1)."""
    d = Doc()
    for prop in ["SOLID", "DOTTED", "DASHED", "CENTER", "PHANTOM"]:
        d.line_desc(prop, 0.2, prop=prop)
    d.line_desc("ERASE", 0.4, end="NONE", prop="ERASE")
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("SILK", "SILKSCREEN", "TOP")
    profile(d, 24, 16)

    def line(y, desc):
        return (
            f'<Set><Features><Location x="0" y="0"/><Line startX="{d.u(1)}" startY="{d.u(y)}" '
            f'endX="{d.u(13)}" endY="{d.u(y)}"><LineDescRef id="{desc}"/></Line></Features></Set>'
        )

    arc = (
        f'<Arc startX="{d.u(16)}" startY="{d.u(11)}" endX="{d.u(22)}" endY="{d.u(11)}" '
        f'centerX="{d.u(19)}" centerY="{d.u(11)}" clockwise="true"><LineDescRef id="DASHED"/></Arc>'
    )
    outline = (
        f"<Polygon>{d.rect(16, 2, 22, 8)}"
        '<LineDescRef id="DOTTED"/><FillDesc fillProperty="HOLLOW"/></Polygon>'
    )
    d.step.append(
        '<LayerFeature layerRef="SILK">'
        + "".join(
            line(y, prop)
            for y, prop in [
                (15, "SOLID"),
                (13, "DOTTED"),
                (11, "DASHED"),
                (9, "CENTER"),
                (7, "PHANTOM"),
            ]
        )
        + f'<Set><Features><Location x="0" y="0"/>{arc}</Features></Set>'
        + f'<Set><Features><Location x="0" y="0"/>{outline}</Features></Set>'
        + "</LayerFeature>"
    )
    erase = (
        f'<Line startX="{d.u(0.5)}" startY="{d.u(3)}" endX="{d.u(13.5)}" endY="{d.u(3)}">'
        '<LineDescRef id="ERASE"/></Line>'
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND">{fill(d, 1, 1, 13, 5)}</Set>'
        f'<Set><Features><Location x="0" y="0"/>{erase}</Features></Set>'
        "</LayerFeature>"
    )
    return d


def slots():
    """A plated slot with pads and a non-plated slot (spec §6.3)."""
    d = Doc()
    d.primitive("LAND", f'<Oval width="{d.u(3.0)}" height="{d.u(1.6)}"/>')
    d.primitive("SLOT_P", f'<Oval width="{d.u(2.2)}" height="{d.u(0.8)}"/>')
    d.primitive("SLOT_N", f'<Oval width="{d.u(0.8)}" height="{d.u(2.4)}"/>')
    two_layers(d)
    profile(d, 10, 4)
    for layer in ("TOP", "BOTTOM"):
        d.step.append(
            f'<LayerFeature layerRef="{layer}">'
            f'<Set net="P" padUsage="TERMINATION">{pad(d, 3, 2, "LAND")}</Set>'
            "</LayerFeature>"
        )
    d.step.append(
        '<LayerFeature layerRef="DRILL">'
        f'<Set net="P"><SlotCavity name="S1" platingStatus="PLATED" plusTol="0" minusTol="0">'
        f'<Location {d.xy(3, 2)}/><StandardPrimitiveRef id="SLOT_P"/></SlotCavity></Set>'
        f'<Set><SlotCavity name="S2" platingStatus="NONPLATED" plusTol="0" minusTol="0">'
        f'<Location {d.xy(7, 2)}/><StandardPrimitiveRef id="SLOT_N"/></SlotCavity></Set>'
        "</LayerFeature>"
    )
    return d


def bottom_placement():
    """Rotated and mirrored bottom-side parts (spec §6.8).

    Pads are placed like KiCad does for mirrored parts: mirror about Y, then rotate
    counter-clockwise.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PIN", f'<Circle diameter="{d.u(0.6)}"/>')
    two_layers(d, drill=False)
    profile(d, 16, 11)
    pins = {"1": (-1.0, -0.5), "2": (1.0, -0.5), "3": (1.0, 1.0)}
    outline = [(-1.5, -1.0), (1.5, -1.0), (1.5, 1.5), (0.5, 1.5), (0.5, 0.0), (-1.5, 0.0)]
    pin_xml = "".join(
        f'<Pin number="{n}"><Location {d.xy(x, y)}/><StandardPrimitiveRef id="PIN"/></Pin>'
        for n, (x, y) in pins.items()
    )
    d.step.append(
        f'<Package name="L3" type="OTHER" pinOne="1" height="{d.u(1.0)}">'
        f'<Outline><Polygon>{d.polygon(outline)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f"{pin_xml}</Package>"
    )
    parts = [
        ("U1", "BOTTOM", 3, 3, 0, True),
        ("U2", "BOTTOM", 8, 3, 30, True),
        ("U3", "BOTTOM", 3, 8, 90, True),
        ("U4", "BOTTOM", 8, 8, 270, True),
        ("U5", "TOP", 13, 5.5, 45, False),
    ]
    features = {"TOP": [], "BOTTOM": []}
    for ref, side, x, y, rot, mirror in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="L3" layerRef="{side}" part="L3-PART" '
            f'mountType="SMT" standoff="0" height="{d.u(1.0)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        a = math.radians(rot)
        for n, (px, py) in pins.items():
            if mirror:
                px = -px
            qx = px * math.cos(a) - py * math.sin(a)
            qy = px * math.sin(a) + py * math.cos(a)
            features[side].append(
                f'<Set net="{ref}_{n}" padUsage="TERMINATION">'
                f'{pad(d, round(x + qx, 6), round(y + qy, 6), "PIN", (ref, n))}</Set>'
            )
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    return d


def placed(x, y, rot, mirror, px, py):
    """A package point placed like KiCad does: mirror about Y, then rotate."""
    if mirror:
        px = -px
    a = math.radians(rot)
    return (
        round(x + px * math.cos(a) - py * math.sin(a), 6),
        round(y + px * math.sin(a) + py * math.cos(a), 6),
    )


def two_pin_package(d, name, drawings=""):
    """A 2-pin package with pins at x = ±0.75 mm and the given drawing elements."""
    d.step.append(
        f'<Package name="{name}" type="OTHER" pinOne="1" height="{d.u(0.6)}">'
        f'<Outline><Polygon>{d.rect(-1.0, -0.5, 1.0, 0.5)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(-0.75, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f'<Pin number="2"><Location {d.xy(0.75, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f"{drawings}</Package>"
    )


def place_two_pin(d, parts, package, features):
    """Places 2-pin parts `(ref, side, x, y, rotation, mirror)` with their pads."""
    for ref, side, x, y, rot, mirror in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="{package}" layerRef="{side}" part="P" '
            f'mountType="SMT" standoff="0" height="{d.u(0.6)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        for n, px in (("1", -0.75), ("2", 0.75)):
            qx, qy = placed(x, y, rot, mirror, px, 0)
            features[side].append(
                f'<Set net="{ref}_{n}" padUsage="TERMINATION">{pad(d, qx, qy, "PAD", (ref, n))}</Set>'
            )


def paste_layer():
    """Paste on the copper surface, through mask and silkscreen; cut by holes (spec §6.11)."""
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("APERTURE", f'<RectCenter width="{d.u(0.8)}" height="{d.u(1.0)}"/>')
    d.primitive("LAND", f'<Circle diameter="{d.u(1.6)}"/>')
    d.primitive("LAND_PASTE", f'<Circle diameter="{d.u(1.4)}"/>')
    d.layer("TOP_SILK", "SILKSCREEN", "TOP")
    d.layer("TOP_PASTE", "SOLDERPASTE", "TOP")
    d.layer("TOP_MASK", "SOLDERMASK", "TOP")
    two_layers(d)
    d.layer("BOT_PASTE", "PASTEMASK", "BOTTOM")
    d.layers.append(
        '<Stackup name="S"><StackupGroup name="G">'
        '<StackupLayer layerOrGroupRef="TOP_PASTE" thickness="0" sequence="1"/>'
        f'<StackupLayer layerOrGroupRef="TOP" thickness="{d.u(0.035)}" sequence="3"/>'
        f'<StackupLayer layerOrGroupRef="BOTTOM" thickness="{d.u(0.035)}" sequence="5"/>'
        f'<StackupLayer layerOrGroupRef="BOT_PASTE" thickness="{d.u(0.15)}" sequence="6"/>'
        "</StackupGroup></Stackup>"
    )
    profile(d, 14, 10)
    two_pin_package(d, "R0805")
    features = {"TOP": [], "BOTTOM": []}
    parts = [("R1", "TOP", 4, 4, 0, False), ("C1", "BOTTOM", 10, 4, 0, True)]
    place_two_pin(d, parts, "R0805", features)
    for layer in ("TOP", "BOTTOM"):
        land = f'<Set net="J1" padUsage="TERMINATION">{pad(d, 7, 7.5, "LAND")}</Set>'
        d.step.append(f'<LayerFeature layerRef="{layer}">{"".join(features[layer])}{land}</LayerFeature>')
    d.step.append(
        '<LayerFeature layerRef="TOP_MASK">'
        f'<Set>{pad(d, 3.25, 4, "PAD")}{pad(d, 4.75, 4, "PAD")}{pad(d, 7, 7.5, "LAND")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP_SILK">'
        f'<Set componentRef="R1">{trace(d, [(2.5, 5.0), (5.5, 5.0)], "SILK")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP_PASTE">'
        f'<Set>{pad(d, 3.25, 4, "APERTURE", ("R1", "1"))}{pad(d, 4.75, 4, "APERTURE", ("R1", "2"))}</Set>'
        f'<Set>{pad(d, 7, 7.5, "LAND_PASTE")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="BOT_PASTE">'
        f'<Set>{pad(d, 10.75, 4, "APERTURE", ("C1", "1"))}{pad(d, 9.25, 4, "APERTURE", ("C1", "2"))}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set net="J1">'
        f'<Hole name="H1" diameter="{d.u(0.8)}" platingStatus="PLATED" plusTol="0" minusTol="0" {d.xy(7, 7.5)}/>'
        "</Set></LayerFeature>"
    )
    return d


def drawing_layers():
    """Courtyard, assembly and documentation layers as stacked drawings (spec §6.12).

    The file's assembly layer has content, so the package's assembly drawing is not drawn
    again (spec §6.13). Empty optional layers and glue layers are left out.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("THIN", 0.05)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    two_layers(d, drill=False)
    d.layer("CRT_TOP", "COURTYARD", "TOP")
    d.layer("FAB_TOP", "ASSEMBLY", "TOP")
    d.layer("FAB_BOT", "ASSEMBLY", "BOTTOM")
    d.layer("NOTES", "DOCUMENT", "NONE")
    d.layer("ECO", "DOCUMENT", "NONE")
    d.layer("GLUE_TOP", "GLUE", "TOP")
    profile(d, 10, 6)
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.5, 1.0, 0.5)}</Polygon>'
        f'<LineDescRef id="THIN"/></Outline></AssemblyDrawing>'
    )
    two_pin_package(d, "R0805", drawing)
    features = {"TOP": [], "BOTTOM": []}
    place_two_pin(d, [("R1", "TOP", 3, 3, 0, False)], "R0805", features)
    d.step.append(f'<LayerFeature layerRef="TOP">{"".join(features["TOP"])}</LayerFeature>')
    outline = (
        f'<Features><Location x="0" y="0"/><Polygon>{d.rect(2.0, 2.5, 4.0, 3.5)}'
        f'<FillDesc fillProperty="HOLLOW"/><LineDescRef id="THIN"/></Polygon></Features>'
    )
    d.step.append(f'<LayerFeature layerRef="FAB_TOP"><Set componentRef="R1">{outline}</Set></LayerFeature>')
    courtyard = (
        f'<Features><Location x="0" y="0"/><Polygon>{d.rect(1.6, 2.2, 4.4, 3.8)}'
        f'<FillDesc fillProperty="HOLLOW"/><LineDescRef id="THIN"/></Polygon></Features>'
    )
    d.step.append(f'<LayerFeature layerRef="CRT_TOP"><Set componentRef="R1">{courtyard}</Set></LayerFeature>')
    d.step.append(
        '<LayerFeature layerRef="FAB_BOT">'
        f'<Set>{trace(d, [(6, 1), (9, 1)], "OUTLINE")}</Set></LayerFeature>'
    )
    d.step.append(
        '<LayerFeature layerRef="NOTES">'
        f'<Set>{trace(d, [(6, 5), (9, 5), (9, 4)], "OUTLINE")}</Set></LayerFeature>'
    )
    d.step.append(
        '<LayerFeature layerRef="GLUE_TOP">'
        f'<Set>{fill(d, 2.8, 2.9, 3.2, 3.1)}</Set></LayerFeature>'
    )
    return d


def assembly_drawing():
    """Synthesized assembly layers from package assembly drawings (spec §6.13)."""
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("ZERO", 0)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("DOT", f'<Circle diameter="{d.u(0.3)}"/>')
    two_layers(d, drill=False)
    profile(d, 14, 8)
    # An outline without FillDesc (drawn as its line, a hairline for zero width), a pin-1
    # dot placed by its Marking's Location, and an arrow.
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.6, 1.0, 0.6)}</Polygon>'
        f'<LineDescRef id="ZERO"/></Outline>'
        f'<Marking markingUsage="NONE"><Location {d.xy(-0.6, 0.3)}/><StandardPrimitiveRef id="DOT"/></Marking>'
        f'<Marking markingUsage="NONE"><Polyline>{d.polygon([(0.2, 0.3), (0.6, 0.0), (0.2, -0.3)], close=False)}'
        f'<LineDescRef id="OUTLINE"/></Polyline></Marking></AssemblyDrawing>'
    )
    two_pin_package(d, "D0805", drawing)
    features = {"TOP": [], "BOTTOM": []}
    parts = [
        ("D1", "TOP", 3, 4, 0, False),
        ("D2", "TOP", 7, 4, 90, False),
        ("D3", "BOTTOM", 11, 4, 30, True),
    ]
    place_two_pin(d, parts, "D0805", features)
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    return d


def package_silkscreen():
    """Package silkscreens where the silkscreen layer has nothing for the part (spec §6.13).

    R1's silkscreen is on the layer and references it; R3's is on the layer without a
    reference (the layer covers it); R2 has nothing on the layer, so its package silkscreen
    is drawn; R4 is on the bottom, which has no silkscreen layer.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.layer("SST", "SILKSCREEN", "TOP")
    two_layers(d, drill=False)
    profile(d, 16, 6)
    bracket = [(-1.3, 0.6), (-1.3, 0.9), (1.3, 0.9), (1.3, 0.6)]
    silk = (
        f'<SilkScreen><Marking markingUsage="NONE"><Polyline>{d.polygon(bracket, close=False)}'
        f'<LineDescRef id="SILK"/></Polyline></Marking></SilkScreen>'
    )
    two_pin_package(d, "R0805", silk)
    features = {"TOP": [], "BOTTOM": []}
    parts = [
        ("R1", "TOP", 3, 3, 0, False),
        ("R2", "TOP", 7, 3, 0, False),
        ("R3", "TOP", 11, 3, 0, False),
        ("R4", "BOTTOM", 14, 3, 0, True),
    ]
    place_two_pin(d, parts, "R0805", features)
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    at = lambda x: [(x + px, 3 + py) for px, py in bracket]
    d.step.append(
        '<LayerFeature layerRef="SST">'
        f'<Set componentRef="R1">{trace(d, at(3), "SILK")}</Set>'
        f'<Set>{trace(d, at(11), "SILK")}</Set>'
        "</LayerFeature>"
    )
    return d


def panel():
    """A panel: steps placed by StepRepeat, nested, rotated and flipped (spec §6.14).

    Step `board` (20 × 12 mm with a notch, datum in its centre) has a part on each side,
    two nets, traces, vias, a mounting hole, silkscreen, paste and package assembly
    drawings. Step `strip` repeats it twice along X in a frame with a local fiducial. Step
    `panel` repeats the strip twice along Y and places two more boards, rotated by 90°, one
    of them flipped (`mirror`), and has rails with global fiducials and tooling holes.
    `Content` lists the board first: the panel converts because no step repeats it.
    """
    d = Doc()
    d.line_desc("TRACE", 0.25)
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("APERTURE", f'<RectCenter width="{d.u(0.8)}" height="{d.u(1.0)}"/>')
    d.primitive("VIA", f'<Circle diameter="{d.u(0.6)}"/>')
    d.primitive("FID", f'<Circle diameter="{d.u(1.0)}"/>')
    d.layer("TOP_SILK", "SILKSCREEN", "TOP")
    d.layer("TOP_PASTE", "SOLDERPASTE", "TOP")
    two_layers(d)
    d.layer("BOT_PASTE", "SOLDERPASTE", "BOTTOM")
    d.layer("BOT_SILK", "SILKSCREEN", "BOTTOM")
    d.step_refs = ["board", "strip", "panel"]

    def contour(outline, cutouts=()):
        holes = "".join(f"<Cutout>{d.rect(*c)}</Cutout>" for c in cutouts)
        return f"<Profile><Polygon>{d.polygon(outline)}</Polygon>{holes}</Profile>"

    def hole(name, x, y, diameter, plating):
        return (
            f'<Hole name="{name}" diameter="{d.u(diameter)}" platingStatus="{plating}" '
            f'plusTol="0" minusTol="0" {d.xy(x, y)}/>'
        )

    def fiducial(element, x, y):
        return f'<{element}><Location {d.xy(x, y)}/><StandardPrimitiveRef id="FID"/></{element}>'

    def silk(points, ref=None):
        component = f' componentRef="{ref}"' if ref else ""
        return f"<Set{component}>{trace(d, points, 'SILK')}</Set>"

    # The board: R1 on top, C1 mirrored on the bottom; nets GND and VCC.
    board = [contour([(0, 0), (20, 0), (20, 9), (17, 9), (17, 12), (0, 12)])]
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.6, 1.0, 0.6)}</Polygon>'
        f'<LineDescRef id="OUTLINE"/></Outline>'
        f'<Marking markingUsage="NONE"><Polyline>{d.polygon([(0.2, 0.3), (0.6, 0.0), (0.2, -0.3)], close=False)}'
        f'<LineDescRef id="OUTLINE"/></Polyline></Marking></AssemblyDrawing>'
    )
    main_step, d.step = d.step, board
    two_pin_package(d, "R0805", drawing)
    d.step = main_step
    parts = [("R1", "TOP", 5, 6, 0, False, ("GND", "VCC")), ("C1", "BOTTOM", 15, 6, 0, True, ("VCC", "GND"))]
    copper = {"TOP": [], "BOTTOM": []}
    paste = {"TOP": [], "BOTTOM": []}
    for ref, side, x, y, rot, mirror, nets in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        board.append(
            f'<Component refDes="{ref}" packageRef="R0805" layerRef="{side}" part="P" '
            f'mountType="SMT" standoff="0" height="{d.u(0.6)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        for (n, px), net in zip((("1", -0.75), ("2", 0.75)), nets):
            qx, qy = placed(x, y, rot, mirror, px, 0)
            copper[side].append(
                f'<Set net="{net}" padUsage="TERMINATION">{pad(d, qx, qy, "PAD", (ref, n))}</Set>'
            )
            paste[side].append(f'<Set>{pad(d, qx, qy, "APERTURE", (ref, n))}</Set>')
    copper["TOP"] += [
        f'<Set net="VCC">{trace(d, [(5.75, 6), (5.75, 9), (10, 9)], "TRACE")}</Set>',
        f'<Set net="GND">{trace(d, [(4.25, 6), (4.25, 2)], "TRACE")}</Set>',
        f'<Set net="GND">{fill(d, 2, 1, 9, 3)}</Set>',
    ]
    copper["BOTTOM"] += [
        f'<Set net="VCC">{trace(d, [(10, 9), (15.75, 9), (15.75, 6)], "TRACE")}</Set>',
        f'<Set net="GND">{trace(d, [(14.25, 6), (14.25, 2), (8, 2)], "TRACE")}</Set>',
    ]
    for side in ("TOP", "BOTTOM"):
        vias = f'<Set net="VCC" padUsage="VIA">{pad(d, 10, 9, "VIA")}</Set>'
        vias += f'<Set net="GND" padUsage="VIA">{pad(d, 8, 2, "VIA")}</Set>'
        board.append(f'<LayerFeature layerRef="{side}">{"".join(copper[side])}{vias}</LayerFeature>')
    board.append(
        '<LayerFeature layerRef="TOP_SILK">'
        + silk([(3.2, 5.0), (6.8, 5.0), (6.8, 7.0), (3.2, 7.0), (3.2, 5.0)], "R1")
        + silk([(1, 10), (3, 10), (1, 11.5), (1, 10)])
        + "</LayerFeature>"
    )
    board.append(
        '<LayerFeature layerRef="BOT_SILK">'
        + silk([(13.2, 5.0), (16.8, 5.0), (16.8, 7.0), (13.2, 7.0), (13.2, 5.0)], "C1")
        + "</LayerFeature>"
    )
    board.append(f'<LayerFeature layerRef="TOP_PASTE">{"".join(paste["TOP"])}</LayerFeature>')
    board.append(f'<LayerFeature layerRef="BOT_PASTE">{"".join(paste["BOTTOM"])}</LayerFeature>')
    board.append(
        '<LayerFeature layerRef="DRILL">'
        f'<Set net="VCC">{hole("V1", 10, 9, 0.3, "VIA")}</Set>'
        f'<Set net="GND">{hole("V2", 8, 2, 0.3, "VIA")}</Set>'
        f'<Set>{hole("M1", 2.5, 8, 1.2, "NONPLATED")}</Set>'
        "</LayerFeature>"
    )
    d.add_step("board", (10, 6), board)

    # The strip: two boards in windows of a frame, a local fiducial on the bar between them.
    d.add_step(
        "strip",
        (0, 0),
        [
            contour([(0, 0), (52, 0), (52, 18), (0, 18)], [(1, 1, 25, 17), (27, 1, 51, 17)]),
            f'<StepRepeat stepRef="board" {d.xy(13, 9)} nx="2" ny="1" dx="{d.u(26)}" dy="0" angle="0" mirror="false"/>',
            f'<LayerFeature layerRef="TOP"><Set>{fiducial("LocalFiducial", 26, 9)}</Set></LayerFeature>',
        ],
    )

    # The panel: rails around two strips, a rotated board and a flipped one.
    d.step.append(
        contour(
            [(0, 0), (100, 0), (100, 46), (0, 46)],
            [(5, 5, 57, 41), (60, 11, 76, 35), (79, 11, 95, 35)],
        )
    )
    d.step.append(
        f'<StepRepeat stepRef="strip" {d.xy(5, 5)} nx="1" ny="2" dx="0" dy="{d.u(18)}" angle="0" mirror="false"/>'
    )
    d.step.append(
        f'<StepRepeat stepRef="board" {d.xy(68, 23)} nx="1" ny="1" dx="0" dy="0" angle="90" mirror="false"/>'
    )
    d.step.append(
        f'<StepRepeat stepRef="board" {d.xy(87, 23)} nx="1" ny="1" dx="0" dy="0" angle="90" mirror="true"/>'
    )
    rails = {
        "TOP": [("GlobalFiducial", 2.5, 2.5), ("GlobalFiducial", 97.5, 2.5), ("GlobalFiducial", 2.5, 43.5)],
        "BOTTOM": [("GlobalFiducial", 2.5, 2.5), ("GoodPanelMark", 97.5, 43.5)],
    }
    for side, marks in rails.items():
        sets = "".join(fiducial(*m) for m in marks)
        d.step.append(f'<LayerFeature layerRef="{side}"><Set>{sets}</Set></LayerFeature>')
    tooling = "".join(
        hole(f"T{k}", x, y, 2.0, "NONPLATED")
        for k, (x, y) in enumerate([(2.5, 23), (97.5, 23), (50, 2.5)], 1)
    )
    d.step.append(f'<LayerFeature layerRef="DRILL"><Set>{tooling}</Set></LayerFeature>')
    return d


def box_model():
    """A 1.6 × 0.8 × 0.5 mm box as a .gltf with an embedded buffer, in metres."""
    (x, z, h) = (0.8e-3, 0.4e-3, 0.5e-3)
    corners = [(sx * x, y, sz * z) for y in (0.0, h) for sz in (-1, 1) for sx in (-1, 1)]
    # Faces as quads of corner indices, counter-clockwise from outside.
    quads = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    indices = [i for a, b, c, e in quads for i in (a, b, c, a, c, e)]
    data = b"".join(struct.pack("<3f", *c) for c in corners)
    data += b"".join(struct.pack("<H", i) for i in indices)
    uri = "data:application/octet-stream;base64," + base64.b64encode(data).decode()
    gltf = {
        "asset": {"version": "2.0", "generator": "boardui samples"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "box", "mesh": 0}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1, "material": 0}]}],
        "materials": [
            {"name": "ceramic", "pbrMetallicRoughness": {"baseColorFactor": [0.55, 0.45, 0.3, 1], "metallicFactor": 0}}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 8, "type": "VEC3",
             "min": [-x, 0, -z], "max": [x, h, z]},
            {"bufferView": 1, "componentType": 5123, "count": len(indices), "type": "SCALAR"},
        ],
        "bufferViews": [
            {"buffer": 0, "byteLength": 96, "target": 34962},
            {"buffer": 0, "byteOffset": 96, "byteLength": 2 * len(indices), "target": 34963},
        ],
        "buffers": [{"byteLength": len(data), "uri": uri}],
    }
    return json.dumps(gltf, indent=1) + "\n"


def colours():
    """Soldermask and silkscreen colours from specs and the colour dictionary (spec §6.10)."""
    d = Doc()
    d.line_desc("TRACE", 0.3)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(1.2)}" height="{d.u(1.4)}"/>')
    d.color("MASK_RGB", 90, 30, 120)
    d.color("COPPER_RGB", 255, 0, 0)
    # Top mask: an explicit colour wins over a colour name in the same spec.
    d.spec(
        "MASK_TOP",
        '<General type="MATERIAL"><Property text="Color : Red"/><ColorRef id="MASK_RGB"/></General>',
    )
    # Top silkscreen: a standard ColorTerm.
    d.spec("SILK_TOP", '<General type="MATERIAL"><ColorTerm name="YELLOW"/></General>')
    # Copper keeps its default even with a colour.
    d.spec("COPPER", '<General type="MATERIAL"><ColorRef id="COPPER_RGB"/></General>')
    # Bottom mask as KiCad 9 writes it: the stack-up refers to `SPEC_SMB`, the spec is `SMB_2`.
    d.spec(
        "SMB_2",
        '<General type="MATERIAL"><Property text="SOLDERMASK"/>'
        '<Property text="Color : Matte Black"/><Property text="Type : Bottom Solder Mask"/></General>',
    )
    # Bottom silkscreen: a name that maps to the default colour.
    d.spec("SILK_BOTTOM", '<General type="MATERIAL"><Property text="Color : White"/></General>')
    d.layer("SST", "SILKSCREEN", "TOP", specs=["SILK_TOP"])
    d.layer("SMT", "SOLDERMASK", "TOP", specs=["MASK_TOP"])
    d.layer("TOP", "CONDUCTOR", "TOP", specs=["COPPER"])
    d.layer("CORE", "DIELCORE", "INTERNAL")
    d.layer("BOTTOM", "CONDUCTOR", "BOTTOM")
    d.layer("SMB", "SOLDERMASK", "BOTTOM")
    d.layer("SSB", "SILKSCREEN", "BOTTOM", specs=["SILK_BOTTOM"])
    stack = [("SST", 0.01), ("SMT", 0.02), ("TOP", 0.035), ("CORE", 1.51)]
    stack += [("BOTTOM", 0.035), ("SMB", 0.02), ("SSB", 0.01)]
    rows = "".join(
        f'<StackupLayer layerOrGroupRef="{name}" thickness="{d.u(t)}" tolPlus="0" tolMinus="0"'
        f' sequence="{i}"' + ('><SpecRef id="SPEC_SMB"/></StackupLayer>' if name == "SMB" else "/>")
        for i, (name, t) in enumerate(stack)
    )
    d.layers.append(
        f'<Stackup name="S" overallThickness="{d.u(1.64)}" tolPlus="0" tolMinus="0" whereMeasured="MASK">'
        f'<StackupGroup name="G" thickness="{d.u(1.64)}" tolPlus="0" tolMinus="0">{rows}</StackupGroup></Stackup>'
    )
    profile(d, 10, 6)
    pads = "".join(pad(d, x, 3, "PAD") for x in (3, 7))
    outline = trace(d, [(1, 1), (9, 1), (9, 5), (1, 5), (1, 1)], "SILK")
    d.step += [
        # Cadence writes the CAD tool's display colour on a layer's first `Set`: not used.
        f'<LayerFeature layerRef="TOP"><Set><ColorRef id="COPPER_RGB"/></Set>'
        f'<Set net="N">{pads}{trace(d, [(3, 3), (7, 3)], "TRACE")}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SMT"><Set>{pads}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SST"><Set>{outline}</Set></LayerFeature>',
        f'<LayerFeature layerRef="BOTTOM"><Set net="N">{fill(d, 2, 2, 8, 4)}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SSB"><Set>{outline}</Set></LayerFeature>',
    ]
    return d


def main():
    samples = {
        "minimal-2layer": minimal("MILLIMETER"),
        "units-inch": minimal("INCH"),
        "units-micron": minimal("MICRON"),
        "overlap-priority": overlap_priority(),
        "negative-polarity": negative_polarity(),
        "zero-width-lines": zero_width_lines(),
        "fiducials": fiducials(),
        "hexagon-moire": hexagon_moire(),
        "hatch-fill": hatch_fill(),
        "line-styles": line_styles(),
        "slots": slots(),
        "bottom-placement": bottom_placement(),
        "paste-layer": paste_layer(),
        "drawing-layers": drawing_layers(),
        "assembly-drawing": assembly_drawing(),
        "package-silkscreen": package_silkscreen(),
        "user-models": minimal("MILLIMETER"),
        "colours": colours(),
        "panel": panel(),
    }
    for name, d in samples.items():
        d.write(HERE / name / f"{name}.xml", name, "panel" if name == "panel" else "board")
    models = HERE / "user-models"
    (models / "r0603.gltf").write_text(box_model())
    mapping = {
        "version": 1,
        "models": [{"match": {"package": "R0603"}, "file": "r0603.gltf"}],
    }
    (models / "models.json").write_text(json.dumps(mapping, indent=2) + "\n")


if __name__ == "__main__":
    main()
