#!/usr/bin/env python3
"""Writes the hand-written samples (spec/samples/README.md).

Each sample is a minimal IPC-2581 rev C file for one spec rule (rev A or B where the rule is
about them). Run from any directory:

    python3 spec/samples/hand-written/generate.py

The script only uses the standard library. Coordinates are written in millimetres here and
converted to each file's units.
"""

import base64
import json
import math
import struct
from pathlib import Path
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent
UNITS = {"MILLIMETER": 1.0, "INCH": 1 / 25.4, "MICRON": 1000.0}


class Doc:
    """An IPC-2581 document in one unit system."""

    def __init__(self, units="MILLIMETER", mode="FABRICATION", revision="C"):
        self.units = units
        self.mode = mode
        self.revision = revision
        # Revision A and B `PadStack`s of the main step; they come before its `Datum`.
        self.pad_stacks = []
        self.lines = {}
        self.standard = {}
        self.layers = []
        self.step = []
        self.colors = {}
        self.specs = []
        # Steps written before the main step: (name, datum, elements).
        self.steps = []
        self.step_refs = None
        self.fonts = {}

    def u(self, mm):
        """A length in mm, formatted in the document's units."""
        v = mm * UNITS[self.units]
        return f"{v:.10g}"

    def xy(self, x, y, prefix=""):
        return f'{prefix}x="{self.u(x)}" {prefix}y="{self.u(y)}"'

    def line_desc(self, name, width, end="ROUND", prop=None):
        prop = f' lineProperty="{prop}"' if prop else ""
        self.lines[name] = f'<LineDesc lineWidth="{self.u(width)}" lineEnd="{end}"{prop}/>'

    def primitive(self, name, xml):
        self.standard[name] = xml

    def font(self, name, xml):
        self.fonts[name] = xml

    def color(self, name, r, g, b):
        self.colors[name] = f'<Color r="{r}" g="{g}" b="{b}"/>'

    def spec(self, name, xml):
        self.specs.append(f'<Spec name="{name}">{xml}</Spec>')

    def layer(self, name, function, side, span=None, specs=()):
        inner = "".join(f'<SpecRef id="{s}"/>' for s in specs)
        inner += f'<Span fromLayer="{span[0]}" toLayer="{span[1]}"/>' if span else ""
        self.layers.append(
            f'<Layer name="{name}" layerFunction="{function}" side="{side}">{inner}</Layer>'
        )

    def polygon(self, points, close=True):
        (x0, y0), rest = points[0], points[1:]
        steps = "".join(f"<PolyStepSegment {self.xy(x, y)}/>" for x, y in rest)
        if close:
            steps += f"<PolyStepSegment {self.xy(x0, y0)}/>"
        return f"<PolyBegin {self.xy(x0, y0)}/>{steps}"

    def rect(self, x0, y0, x1, y1):
        return self.polygon([(x0, y0), (x1, y0), (x1, y1), (x0, y1)])

    def add_step(self, name, datum, elements):
        self.steps.append((name, datum, elements))

    def write(self, path, name, step_name="board"):
        dict_units = f'units="{self.units}"'
        lines = "".join(
            f'<EntryLineDesc id="{k}">{v}</EntryLineDesc>' for k, v in self.lines.items()
        )
        standard = "".join(
            f'<EntryStandard id="{k}">{v}</EntryStandard>' for k, v in self.standard.items()
        )
        colors = "".join(f'<EntryColor id="{k}">{v}</EntryColor>' for k, v in self.colors.items())
        colors = f"\n    <DictionaryColor>{colors}</DictionaryColor>" if colors else ""
        fonts = "".join(
            f'\n      <EntryFont id="{k}">{v}</EntryFont>' for k, v in self.fonts.items()
        )
        if fonts:
            fonts = f"\n    <DictionaryFont {dict_units}>{fonts}\n    </DictionaryFont>"
        header = f'<CadHeader units="{self.units}"/>'
        if self.specs:
            specs = "".join(f"\n      {s}" for s in self.specs)
            header = f'<CadHeader units="{self.units}">{specs}\n    </CadHeader>'
        step_refs = "".join(
            f'\n    <StepRef name="{s}"/>' for s in (self.step_refs or [step_name])
        )
        steps = "".join(
            f'\n      <Step name="{s}">\n        <Datum {self.xy(*datum)}/>'
            + "".join(f"\n        {e}" for e in elements)
            + "\n      </Step>"
            for s, datum, elements in self.steps
        )
        xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {name}: hand-written boardui sample, generated by generate.py. -->
<IPC-2581 revision="{self.revision}" xmlns="http://webstds.ipc.org/2581">
  <Content>
    <FunctionMode mode="{self.mode}"/>{step_refs}
    <DictionaryLineDesc {dict_units}>{lines}</DictionaryLineDesc>{fonts}
    <DictionaryStandard {dict_units}>{standard}</DictionaryStandard>{colors}
  </Content>
  <Ecad name="{name}">
    {header}
    <CadData>
      {chr(10).join("      " + l for l in self.layers).strip()}{steps}
      <Step name="{step_name}">{"".join(chr(10) + "        " + p for p in self.pad_stacks)}
        <Datum x="0" y="0"/>
{chr(10).join("        " + s for s in self.step)}
      </Step>
    </CadData>
  </Ecad>
</IPC-2581>
"""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(xml)


def two_layers(d, drill=True):
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("BOTTOM", "CONDUCTOR", "BOTTOM")
    if drill:
        d.layer("DRILL", "DRILL", "ALL", span=("TOP", "BOTTOM"))


def profile(d, w, h):
    d.step.append(f"<Profile><Polygon>{d.rect(0, 0, w, h)}</Polygon></Profile>")


def pad(d, x, y, shape, pin=None, rotation=None):
    xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
    pin_ref = f'<PinRef componentRef="{pin[0]}" pin="{pin[1]}"/>' if pin else ""
    return (
        f"<Pad>{xform}<Location {d.xy(x, y)}/>"
        f'<StandardPrimitiveRef id="{shape}"/>{pin_ref}</Pad>'
    )


def trace(d, points, line):
    return (
        f'<Features><Location x="0" y="0"/><Polyline>{d.polygon(points, close=False)}'
        f'<LineDescRef id="{line}"/></Polyline></Features>'
    )


def fill(d, x0, y0, x1, y1):
    return (
        f'<Features><Location x="0" y="0"/><Contour><Polygon>{d.rect(x0, y0, x1, y1)}'
        f"</Polygon></Contour></Features>"
    )


def minimal(units, revision="C"):
    """One resistor, two pads, one trace, one via (spec §4–§8)."""
    d = Doc(units, revision=revision)
    d.line_desc("TRACE", 0.25)
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.0)}"/>')
    d.primitive("VIA", f'<Circle diameter="{d.u(0.6)}"/>')
    two_layers(d)
    profile(d, 10, 6)
    d.step.append(
        f'<Package name="R0603" type="RESISTOR" pinOne="1" height="{d.u(0.5)}">'
        f'<Outline><Polygon>{d.rect(-1.2, -0.6, 1.2, 0.6)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(-0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f'<Pin number="2"><Location {d.xy(0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f"</Package>"
    )
    d.step.append(
        f'<Component refDes="R1" packageRef="R0603" layerRef="TOP" part="RES-10K" '
        f'mountType="SMT" standoff="0" height="{d.u(0.5)}"><Location {d.xy(3, 3)}/></Component>'
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="N1" padUsage="TERMINATION">{pad(d, 2.2, 3, "PAD", ("R1", "1"))}</Set>'
        f'<Set net="N2" padUsage="TERMINATION">{pad(d, 3.8, 3, "PAD", ("R1", "2"))}</Set>'
        f'<Set net="N2">{trace(d, [(3.8, 3), (7, 3)], "TRACE")}</Set>'
        f'<Set net="N2" padUsage="VIA">{pad(d, 7, 3, "VIA")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="BOTTOM">'
        f'<Set net="N2" padUsage="VIA">{pad(d, 7, 3, "VIA")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set net="N2">'
        f'<Hole name="H1" diameter="{d.u(0.3)}" platingStatus="VIA" plusTol="0" minusTol="0" {d.xy(7, 3)}/>'
        "</Set></LayerFeature>"
    )
    return d


def pad_stack(d, net, pads, hole=None):
    """A revision A/B `PadStack`: `pads` are `(layer, x, y, shape, pin)`, `hole` is
    `(name, x, y, diameter, platingStatus)` spanning TOP to BOTTOM."""
    inner = ""
    if hole:
        name, x, y, diameter, plating = hole
        inner += (
            f'<LayerHole name="{name}" diameter="{d.u(diameter)}" platingStatus="{plating}" '
            f'plusTol="0" minusTol="0" {d.xy(x, y)}><Span fromLayer="TOP" toLayer="BOTTOM"/></LayerHole>'
        )
    for layer, x, y, shape, pin in pads:
        pin_ref = f'<PinRef componentRef="{pin[0]}" pin="{pin[1]}"/>' if pin else ""
        inner += (
            f'<LayerPad layerRef="{layer}"><Location {d.xy(x, y)}/>'
            f'<StandardPrimitiveRef id="{shape}"/>{pin_ref}</LayerPad>'
        )
    net = f' net="{net}"' if net else ""
    d.pad_stacks.append(f"<PadStack{net}>{inner}</PadStack>")


def pad_stacks():
    """`minimal-2layer` as revision B `PadStack`s, plus a mounting hole, without a drill
    layer: pad and via features with their nets and pins, holes on a synthesized drill layer
    (spec §6.3)."""
    d = minimal("MILLIMETER", revision="B")
    d.layers = [l for l in d.layers if 'name="DRILL"' not in l]
    d.step = [e for e in d.step if not e.startswith("<LayerFeature")]
    pad_stack(d, "N1", [("TOP", 2.2, 3, "PAD", ("R1", "1"))])
    pad_stack(d, "N2", [("TOP", 3.8, 3, "PAD", ("R1", "2"))])
    pad_stack(
        d, "N2", [("TOP", 7, 3, "VIA", None), ("BOTTOM", 7, 3, "VIA", None)], ("V1", 7, 3, 0.3, "VIA")
    )
    pad_stack(d, None, [], ("MH1", 8.5, 1.2, 1.0, "NONPLATED"))
    d.step.append(
        f'<LayerFeature layerRef="TOP"><Set net="N2">{trace(d, [(3.8, 3), (7, 3)], "TRACE")}</Set></LayerFeature>'
    )
    return d


def pad_stacks_drill_layer():
    """Revision A `PadStack` holes that an Altium-style `Drill Guide` layer also has: the drill
    layer's hole is kept and takes the padstack's net; a hole it lacks is added to it (spec
    §6.3)."""
    d = Doc(revision="A")
    d.primitive("VIA", f'<Circle diameter="{d.u(0.6)}"/>')
    d.layer("TOP", "SIGNAL", "TOP")
    d.layer("BOTTOM", "SIGNAL", "BOTTOM")
    d.layer("Drill Guide", "DRILL", "INTERNAL")
    profile(d, 8, 4)
    for name, x in (("V1", 2), ("V2", 6)):
        lands = [("TOP", x, 2, "VIA", None), ("BOTTOM", x, 2, "VIA", None)]
        pad_stack(d, "GND", lands, (name, x, 2, 0.3, "VIA"))
    d.step.append(
        '<LayerFeature layerRef="Drill Guide"><Set>'
        f'<Hole name="Via Hole Drill 0" diameter="{d.u(0.3)}" platingStatus="VIA" plusTol="0" minusTol="0" {d.xy(2, 2)}/>'
        "</Set></LayerFeature>"
    )
    return d


def conductor_core():
    """Altium's core: a `CONDUCTOR` layer with `side="NONE"` and `materialType="FR-4"` in the
    revision A stack-up is a dielectric (spec §6.4)."""
    d = Doc(revision="A")
    d.line_desc("TRACE", 0.25)
    d.layer("Top Layer", "SIGNAL", "TOP")
    d.layer("Dielectric 1", "CONDUCTOR", "NONE")
    d.layer("Bottom Layer", "SIGNAL", "BOTTOM")
    rows = "".join(
        f'<StackupLayer layerOrGroupRef="{name}" materialType="{material}" thickness="{d.u(t)}"/>'
        for name, material, t in (
            ("Top Layer", "Copper", 0.035),
            ("Dielectric 1", "FR-4", 0.32),
            ("Bottom Layer", "Copper", 0.035),
        )
    )
    d.layers.append(f'<Stackup name="S"><StackupGroup name="G">{rows}</StackupGroup></Stackup>')
    profile(d, 6, 4)
    for layer, y in (("Top Layer", 1.5), ("Bottom Layer", 2.5)):
        d.step.append(
            f'<LayerFeature layerRef="{layer}"><Set net="N">{trace(d, [(1, y), (5, y)], "TRACE")}</Set></LayerFeature>'
        )
    return d


def overlap_priority():
    """Pad over trace over plane, and ties in document order (spec §6.2)."""
    d = Doc()
    d.line_desc("WIDE", 0.5)
    d.line_desc("THIN", 0.3)
    d.primitive("PAD", f'<Circle diameter="{d.u(1.2)}"/>')
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 10, 4)
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        # 0: a plane, the lowest priority.
        f'<Set net="GND">{fill(d, 0, 0, 8, 4)}</Set>'
        # 1: a trace across the plane.
        f'<Set net="SIG">{trace(d, [(1, 2), (7, 2)], "WIDE")}</Set>'
        # 2: a pad on the trace.
        f'<Set net="SIG" padUsage="TERMINATION">{pad(d, 4, 2, "PAD")}</Set>'
        # 3: a second plane overlapping the first: the earlier one keeps the overlap.
        f'<Set net="GND">{fill(d, 6, 1, 10, 3)}</Set>'
        # 4: a second trace crossing the first: the earlier one keeps the crossing.
        f'<Set net="SIG2">{trace(d, [(2, 3.5), (2, 0.5)], "THIN")}</Set>'
        "</LayerFeature>"
    )
    return d


def negative_polarity():
    """A plane with negative cut-outs; later features are not cut (spec §6.2)."""
    d = Doc()
    d.line_desc("TRACE", 0.3)
    d.primitive("HOLE", f'<Circle diameter="{d.u(1.5)}"/>')
    d.primitive("SLOT", f'<RectCenter width="{d.u(1.0)}" height="{d.u(3.0)}"/>')
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 8, 4)
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND">{fill(d, 0, 0, 8, 4)}</Set>'
        f'<Set polarity="NEGATIVE"><Features><Location {d.xy(2, 2)}/><StandardPrimitiveRef id="HOLE"/></Features></Set>'
        f'<Set polarity="NEGATIVE"><Features><Location {d.xy(6, 2)}/><StandardPrimitiveRef id="SLOT"/></Features></Set>'
        f'<Set net="SIG">{trace(d, [(1, 2), (7, 2)], "TRACE")}</Set>'
        "</LayerFeature>"
    )
    return d


def zero_width_lines():
    """Silkscreen strokes with zero-width lines are 0.1 mm hairlines (spec §6.1)."""
    d = Doc()
    d.line_desc("ZERO", 0)
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("SILK", "SILKSCREEN", "TOP")
    profile(d, 6, 4)
    line = (
        f'<Line startX="{d.u(1)}" startY="{d.u(3)}" endX="{d.u(3)}" endY="{d.u(3)}">'
        '<LineDescRef id="ZERO"/></Line>'
    )
    d.step.append(
        '<LayerFeature layerRef="SILK">'
        f'<Set>{trace(d, [(1, 1), (5, 1), (5, 3)], "ZERO")}</Set>'
        f'<Set><Features><Location x="0" y="0"/>{line}</Features></Set>'
        "</LayerFeature>"
    )
    return d


def fiducials():
    """The four fiducial elements are copper features of kind FIDUCIAL (spec §6.2, §8.2)."""
    d = Doc()
    d.primitive("FID", f'<Circle diameter="{d.u(1.0)}"/>')
    two_layers(d, drill=False)
    profile(d, 12, 8)

    def fiducial(element, x, y, shape, rotation=None):
        xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
        return f"<{element}>{xform}<Location {d.xy(x, y)}/>{shape}</{element}>"

    d.step.append(
        '<LayerFeature layerRef="TOP"><Set>'
        + fiducial("GlobalFiducial", 1.5, 1.5, '<StandardPrimitiveRef id="FID"/>')
        + fiducial("GlobalFiducial", 10.5, 6.5, '<StandardPrimitiveRef id="FID"/>')
        + fiducial("LocalFiducial", 4, 4, f'<Circle diameter="{d.u(0.6)}"/>')
        + fiducial("BadBoardMark", 8, 4, f'<Circle diameter="{d.u(1.5)}"/>')
        + fiducial(
            "GoodPanelMark",
            10.5,
            1.5,
            f'<RectCenter width="{d.u(1.0)}" height="{d.u(1.0)}"/>',
            rotation=45,
        )
        + "</Set></LayerFeature>"
    )
    return d


def hexagon_moire():
    """Hexagon (corner up, `length` across corners) and Moire primitives (spec §6.1)."""
    d = Doc()
    d.line_desc("THIN", 0.15)
    d.primitive("HEX", f'<Hexagon length="{d.u(2.0)}"/>')
    d.primitive(
        "HEX_HOLLOW",
        f'<Hexagon length="{d.u(2.0)}"><LineDescRef id="THIN"/>'
        '<FillDesc fillProperty="HOLLOW"/></Hexagon>',
    )
    d.primitive(
        "MOIRE",
        f'<Moire diameter="{d.u(4.0)}" ringWidth="{d.u(0.2)}" ringGap="{d.u(0.6)}" '
        f'ringNumber="3" lineWidth="{d.u(0.15)}" lineLength="{d.u(5.0)}" lineAngle="0"/>',
    )
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 14, 6)

    def feature(x, y, shape, rotation=None):
        xform = f'<Xform rotation="{rotation:g}"/>' if rotation else ""
        return (
            f"<Set><Features>{xform}<Location {d.xy(x, y)}/>"
            f'<StandardPrimitiveRef id="{shape}"/></Features></Set>'
        )

    d.step.append(
        '<LayerFeature layerRef="TOP">'
        + feature(2, 3, "HEX")
        + feature(5, 3, "HEX", rotation=30)
        + feature(8, 3, "HEX_HOLLOW")
        + feature(11.5, 3, "MOIRE")
        + "</LayerFeature>"
    )
    return d


def primitive_xform():
    """Standard primitives with their own `Xform` (rev B; Allegro 17.4 writes it in rev C
    files): it turns the primitive in its own frame, before the pad places it (spec §6.1).

    Top row: 2-pin parts at 0°, 90° and 30° whose pads carry the part's rotation and use a
    rectangle or oval turned upright by its own `Xform`, so every pad lies across the pin axis.
    Bottom row: a rectangle chamfered at its upper-right corner, mirrored by its own `Xform`
    (chamfer upper left), and an oval moved 0.5 mm along its X axis, each in a pad at 0° and 90°.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.primitive(
        "RECT_R90",
        f'<RectCenter width="{d.u(2.0)}" height="{d.u(1.0)}"><Xform rotation="90"/></RectCenter>',
    )
    d.primitive(
        "OVAL_R270",
        f'<Oval width="{d.u(2.0)}" height="{d.u(0.8)}"><Xform rotation="270"/></Oval>',
    )
    d.primitive(
        "CHAM_MIRROR",
        f'<RectCham width="{d.u(2.0)}" height="{d.u(1.0)}" chamfer="{d.u(0.5)}" '
        'upperLeft="false" lowerRight="false" lowerLeft="false"><Xform mirror="true"/></RectCham>',
    )
    d.primitive(
        "OVAL_OFFSET",
        f'<Oval width="{d.u(1.6)}" height="{d.u(0.8)}"><Xform xOffset="{d.u(0.5)}"/></Oval>',
    )
    two_layers(d, drill=False)
    profile(d, 20, 11)
    for name, shape in (("P_RECT", "RECT_R90"), ("P_OVAL", "OVAL_R270")):
        d.step.append(
            f'<Package name="{name}" type="OTHER" pinOne="1" height="{d.u(0.6)}">'
            f'<Outline><Polygon>{d.rect(-0.9, -0.6, 0.9, 0.6)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
            f'<Pin number="1"><Location {d.xy(-1.5, 0)}/><StandardPrimitiveRef id="{shape}"/></Pin>'
            f'<Pin number="2"><Location {d.xy(1.5, 0)}/><StandardPrimitiveRef id="{shape}"/></Pin>'
            "</Package>"
        )
    sets = []
    for ref, package, shape, x, y, rot in (
        ("U1", "P_RECT", "RECT_R90", 4, 8, 0),
        ("U2", "P_RECT", "RECT_R90", 10, 8, 90),
        ("U3", "P_OVAL", "OVAL_R270", 16, 8, 30),
    ):
        xform = f'<Xform rotation="{rot:g}"/>' if rot else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="{package}" layerRef="TOP" part="P" '
            f'mountType="SMT" standoff="0" height="{d.u(0.6)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        for n, px in (("1", -1.5), ("2", 1.5)):
            qx, qy = placed(x, y, rot, False, px, 0)
            sets.append(
                f'<Set net="{ref}_{n}" padUsage="TERMINATION">'
                f"{pad(d, qx, qy, shape, (ref, n), rotation=rot)}</Set>"
            )
    for shape, x, rot in (
        ("CHAM_MIRROR", 3, 0),
        ("CHAM_MIRROR", 7, 90),
        ("OVAL_OFFSET", 12, 0),
        ("OVAL_OFFSET", 16, 90),
    ):
        sets.append(f'<Set padUsage="TERMINATION">{pad(d, x, 3, shape, rotation=rot)}</Set>')
    d.step.append(f'<LayerFeature layerRef="TOP">{"".join(sets)}</LayerFeature>')
    return d


def hatch_fill():
    """HATCH and MESH fills are lines clipped to the area, plus the outline (spec §6.1)."""
    d = Doc()
    d.line_desc("EDGE", 0.3)
    d.primitive(
        "MESHED",
        f'<Circle diameter="{d.u(5.0)}"><FillDesc fillProperty="MESH" lineWidth="{d.u(0.2)}" '
        f'pitch1="{d.u(0.8)}" angle1="0" pitch2="{d.u(0.8)}" angle2="90"/></Circle>',
    )
    d.layer("TOP", "CONDUCTOR", "TOP")
    profile(d, 16, 7)
    hatched = (
        f"<Polygon>{d.polygon([(1, 1), (8, 1), (8, 6), (4, 6), (1, 3)])}"
        '<LineDescRef id="EDGE"/>'
        f'<FillDesc fillProperty="HATCH" lineWidth="{d.u(0.2)}" pitch1="{d.u(0.7)}" angle1="45"/>'
        "</Polygon>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND"><Features><Location x="0" y="0"/>{hatched}</Features></Set>'
        f'<Set net="GND"><Features><Location {d.xy(12, 3.5)}/>'
        '<StandardPrimitiveRef id="MESHED"/></Features></Set>'
        "</LayerFeature>"
    )
    return d


def line_styles():
    """lineProperty patterns along lines, arcs and outlines, and an ERASE line (spec §6.1)."""
    d = Doc()
    for prop in ["SOLID", "DOTTED", "DASHED", "CENTER", "PHANTOM"]:
        d.line_desc(prop, 0.2, prop=prop)
    d.line_desc("ERASE", 0.4, end="NONE", prop="ERASE")
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("SILK", "SILKSCREEN", "TOP")
    profile(d, 24, 16)

    def line(y, desc):
        return (
            f'<Set><Features><Location x="0" y="0"/><Line startX="{d.u(1)}" startY="{d.u(y)}" '
            f'endX="{d.u(13)}" endY="{d.u(y)}"><LineDescRef id="{desc}"/></Line></Features></Set>'
        )

    arc = (
        f'<Arc startX="{d.u(16)}" startY="{d.u(11)}" endX="{d.u(22)}" endY="{d.u(11)}" '
        f'centerX="{d.u(19)}" centerY="{d.u(11)}" clockwise="true"><LineDescRef id="DASHED"/></Arc>'
    )
    outline = (
        f"<Polygon>{d.rect(16, 2, 22, 8)}"
        '<LineDescRef id="DOTTED"/><FillDesc fillProperty="HOLLOW"/></Polygon>'
    )
    d.step.append(
        '<LayerFeature layerRef="SILK">'
        + "".join(
            line(y, prop)
            for y, prop in [
                (15, "SOLID"),
                (13, "DOTTED"),
                (11, "DASHED"),
                (9, "CENTER"),
                (7, "PHANTOM"),
            ]
        )
        + f'<Set><Features><Location x="0" y="0"/>{arc}</Features></Set>'
        + f'<Set><Features><Location x="0" y="0"/>{outline}</Features></Set>'
        + "</LayerFeature>"
    )
    erase = (
        f'<Line startX="{d.u(0.5)}" startY="{d.u(3)}" endX="{d.u(13.5)}" endY="{d.u(3)}">'
        '<LineDescRef id="ERASE"/></Line>'
    )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND">{fill(d, 1, 1, 13, 5)}</Set>'
        f'<Set><Features><Location x="0" y="0"/>{erase}</Features></Set>'
        "</LayerFeature>"
    )
    return d


def slots():
    """A plated slot with pads and a non-plated slot (spec §6.3)."""
    d = Doc()
    d.primitive("LAND", f'<Oval width="{d.u(3.0)}" height="{d.u(1.6)}"/>')
    d.primitive("SLOT_P", f'<Oval width="{d.u(2.2)}" height="{d.u(0.8)}"/>')
    d.primitive("SLOT_N", f'<Oval width="{d.u(0.8)}" height="{d.u(2.4)}"/>')
    two_layers(d)
    profile(d, 10, 4)
    for layer in ("TOP", "BOTTOM"):
        d.step.append(
            f'<LayerFeature layerRef="{layer}">'
            f'<Set net="P" padUsage="TERMINATION">{pad(d, 3, 2, "LAND")}</Set>'
            "</LayerFeature>"
        )
    d.step.append(
        '<LayerFeature layerRef="DRILL">'
        f'<Set net="P"><SlotCavity name="S1" platingStatus="PLATED" plusTol="0" minusTol="0">'
        f'<Location {d.xy(3, 2)}/><StandardPrimitiveRef id="SLOT_P"/></SlotCavity></Set>'
        f'<Set><SlotCavity name="S2" platingStatus="NONPLATED" plusTol="0" minusTol="0">'
        f'<Location {d.xy(7, 2)}/><StandardPrimitiveRef id="SLOT_N"/></SlotCavity></Set>'
        "</LayerFeature>"
    )
    return d


def bottom_placement():
    """Rotated and mirrored bottom-side parts (spec §6.8).

    Pads are placed like KiCad does for mirrored parts: mirror about Y, then rotate
    counter-clockwise.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PIN", f'<Circle diameter="{d.u(0.6)}"/>')
    two_layers(d, drill=False)
    profile(d, 16, 11)
    pins = {"1": (-1.0, -0.5), "2": (1.0, -0.5), "3": (1.0, 1.0)}
    outline = [(-1.5, -1.0), (1.5, -1.0), (1.5, 1.5), (0.5, 1.5), (0.5, 0.0), (-1.5, 0.0)]
    pin_xml = "".join(
        f'<Pin number="{n}"><Location {d.xy(x, y)}/><StandardPrimitiveRef id="PIN"/></Pin>'
        for n, (x, y) in pins.items()
    )
    d.step.append(
        f'<Package name="L3" type="OTHER" pinOne="1" height="{d.u(1.0)}">'
        f'<Outline><Polygon>{d.polygon(outline)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f"{pin_xml}</Package>"
    )
    parts = [
        ("U1", "BOTTOM", 3, 3, 0, True),
        ("U2", "BOTTOM", 8, 3, 30, True),
        ("U3", "BOTTOM", 3, 8, 90, True),
        ("U4", "BOTTOM", 8, 8, 270, True),
        ("U5", "TOP", 13, 5.5, 45, False),
    ]
    features = {"TOP": [], "BOTTOM": []}
    for ref, side, x, y, rot, mirror in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="L3" layerRef="{side}" part="L3-PART" '
            f'mountType="SMT" standoff="0" height="{d.u(1.0)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        a = math.radians(rot)
        for n, (px, py) in pins.items():
            if mirror:
                px = -px
            qx = px * math.cos(a) - py * math.sin(a)
            qy = px * math.sin(a) + py * math.cos(a)
            features[side].append(
                f'<Set net="{ref}_{n}" padUsage="TERMINATION">'
                f'{pad(d, round(x + qx, 6), round(y + qy, 6), "PIN", (ref, n))}</Set>'
            )
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    return d


def placed(x, y, rot, mirror, px, py):
    """A package point placed like KiCad does: mirror about Y, then rotate."""
    if mirror:
        px = -px
    a = math.radians(rot)
    return (
        round(x + px * math.cos(a) - py * math.sin(a), 6),
        round(y + px * math.sin(a) + py * math.cos(a), 6),
    )


def two_pin_package(d, name, drawings=""):
    """A 2-pin package with pins at x = ±0.75 mm and the given drawing elements."""
    d.step.append(
        f'<Package name="{name}" type="OTHER" pinOne="1" height="{d.u(0.6)}">'
        f'<Outline><Polygon>{d.rect(-1.0, -0.5, 1.0, 0.5)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(-0.75, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f'<Pin number="2"><Location {d.xy(0.75, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f"{drawings}</Package>"
    )


def place_two_pin(d, parts, package, features):
    """Places 2-pin parts `(ref, side, x, y, rotation, mirror)` with their pads."""
    for ref, side, x, y, rot, mirror in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="{package}" layerRef="{side}" part="P" '
            f'mountType="SMT" standoff="0" height="{d.u(0.6)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        for n, px in (("1", -0.75), ("2", 0.75)):
            qx, qy = placed(x, y, rot, mirror, px, 0)
            features[side].append(
                f'<Set net="{ref}_{n}" padUsage="TERMINATION">{pad(d, qx, qy, "PAD", (ref, n))}</Set>'
            )


def paste_layer():
    """Paste on the copper surface, through mask and silkscreen; cut by holes (spec §6.11)."""
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("APERTURE", f'<RectCenter width="{d.u(0.8)}" height="{d.u(1.0)}"/>')
    d.primitive("LAND", f'<Circle diameter="{d.u(1.6)}"/>')
    d.primitive("LAND_PASTE", f'<Circle diameter="{d.u(1.4)}"/>')
    d.layer("TOP_SILK", "SILKSCREEN", "TOP")
    d.layer("TOP_PASTE", "SOLDERPASTE", "TOP")
    d.layer("TOP_MASK", "SOLDERMASK", "TOP")
    two_layers(d)
    d.layer("BOT_PASTE", "PASTEMASK", "BOTTOM")
    d.layers.append(
        '<Stackup name="S"><StackupGroup name="G">'
        '<StackupLayer layerOrGroupRef="TOP_PASTE" thickness="0" sequence="1"/>'
        f'<StackupLayer layerOrGroupRef="TOP" thickness="{d.u(0.035)}" sequence="3"/>'
        f'<StackupLayer layerOrGroupRef="BOTTOM" thickness="{d.u(0.035)}" sequence="5"/>'
        f'<StackupLayer layerOrGroupRef="BOT_PASTE" thickness="{d.u(0.15)}" sequence="6"/>'
        "</StackupGroup></Stackup>"
    )
    profile(d, 14, 10)
    two_pin_package(d, "R0805")
    features = {"TOP": [], "BOTTOM": []}
    parts = [("R1", "TOP", 4, 4, 0, False), ("C1", "BOTTOM", 10, 4, 0, True)]
    place_two_pin(d, parts, "R0805", features)
    for layer in ("TOP", "BOTTOM"):
        land = f'<Set net="J1" padUsage="TERMINATION">{pad(d, 7, 7.5, "LAND")}</Set>'
        d.step.append(f'<LayerFeature layerRef="{layer}">{"".join(features[layer])}{land}</LayerFeature>')
    d.step.append(
        '<LayerFeature layerRef="TOP_MASK">'
        f'<Set>{pad(d, 3.25, 4, "PAD")}{pad(d, 4.75, 4, "PAD")}{pad(d, 7, 7.5, "LAND")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP_SILK">'
        f'<Set componentRef="R1">{trace(d, [(2.5, 5.0), (5.5, 5.0)], "SILK")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="TOP_PASTE">'
        f'<Set>{pad(d, 3.25, 4, "APERTURE", ("R1", "1"))}{pad(d, 4.75, 4, "APERTURE", ("R1", "2"))}</Set>'
        f'<Set>{pad(d, 7, 7.5, "LAND_PASTE")}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="BOT_PASTE">'
        f'<Set>{pad(d, 10.75, 4, "APERTURE", ("C1", "1"))}{pad(d, 9.25, 4, "APERTURE", ("C1", "2"))}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set net="J1">'
        f'<Hole name="H1" diameter="{d.u(0.8)}" platingStatus="PLATED" plusTol="0" minusTol="0" {d.xy(7, 7.5)}/>'
        "</Set></LayerFeature>"
    )
    return d


def drawing_layers():
    """Courtyard, assembly and documentation layers as stacked drawings (spec §6.12).

    The file's assembly layer has content, so the package's assembly drawing is not drawn
    again (spec §6.13). Empty optional layers and glue layers are left out.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("THIN", 0.05)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    two_layers(d, drill=False)
    d.layer("CRT_TOP", "COURTYARD", "TOP")
    d.layer("FAB_TOP", "ASSEMBLY", "TOP")
    d.layer("FAB_BOT", "ASSEMBLY", "BOTTOM")
    d.layer("NOTES", "DOCUMENT", "NONE")
    d.layer("ECO", "DOCUMENT", "NONE")
    d.layer("GLUE_TOP", "GLUE", "TOP")
    profile(d, 10, 6)
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.5, 1.0, 0.5)}</Polygon>'
        f'<LineDescRef id="THIN"/></Outline></AssemblyDrawing>'
    )
    two_pin_package(d, "R0805", drawing)
    features = {"TOP": [], "BOTTOM": []}
    place_two_pin(d, [("R1", "TOP", 3, 3, 0, False)], "R0805", features)
    d.step.append(f'<LayerFeature layerRef="TOP">{"".join(features["TOP"])}</LayerFeature>')
    outline = (
        f'<Features><Location x="0" y="0"/><Polygon>{d.rect(2.0, 2.5, 4.0, 3.5)}'
        f'<FillDesc fillProperty="HOLLOW"/><LineDescRef id="THIN"/></Polygon></Features>'
    )
    d.step.append(f'<LayerFeature layerRef="FAB_TOP"><Set componentRef="R1">{outline}</Set></LayerFeature>')
    courtyard = (
        f'<Features><Location x="0" y="0"/><Polygon>{d.rect(1.6, 2.2, 4.4, 3.8)}'
        f'<FillDesc fillProperty="HOLLOW"/><LineDescRef id="THIN"/></Polygon></Features>'
    )
    d.step.append(f'<LayerFeature layerRef="CRT_TOP"><Set componentRef="R1">{courtyard}</Set></LayerFeature>')
    d.step.append(
        '<LayerFeature layerRef="FAB_BOT">'
        f'<Set>{trace(d, [(6, 1), (9, 1)], "OUTLINE")}</Set></LayerFeature>'
    )
    d.step.append(
        '<LayerFeature layerRef="NOTES">'
        f'<Set>{trace(d, [(6, 5), (9, 5), (9, 4)], "OUTLINE")}</Set></LayerFeature>'
    )
    d.step.append(
        '<LayerFeature layerRef="GLUE_TOP">'
        f'<Set>{fill(d, 2.8, 2.9, 3.2, 3.1)}</Set></LayerFeature>'
    )
    return d


def assembly_drawing():
    """Synthesized assembly layers from package assembly drawings (spec §6.13)."""
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("ZERO", 0)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("DOT", f'<Circle diameter="{d.u(0.3)}"/>')
    two_layers(d, drill=False)
    profile(d, 14, 8)
    # An outline without FillDesc (drawn as its line, a hairline for zero width), a pin-1
    # dot placed by its Marking's Location, and an arrow.
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.6, 1.0, 0.6)}</Polygon>'
        f'<LineDescRef id="ZERO"/></Outline>'
        f'<Marking markingUsage="NONE"><Location {d.xy(-0.6, 0.3)}/><StandardPrimitiveRef id="DOT"/></Marking>'
        f'<Marking markingUsage="NONE"><Polyline>{d.polygon([(0.2, 0.3), (0.6, 0.0), (0.2, -0.3)], close=False)}'
        f'<LineDescRef id="OUTLINE"/></Polyline></Marking></AssemblyDrawing>'
    )
    two_pin_package(d, "D0805", drawing)
    features = {"TOP": [], "BOTTOM": []}
    parts = [
        ("D1", "TOP", 3, 4, 0, False),
        ("D2", "TOP", 7, 4, 90, False),
        ("D3", "BOTTOM", 11, 4, 30, True),
    ]
    place_two_pin(d, parts, "D0805", features)
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    return d


def package_silkscreen():
    """Package silkscreens where the silkscreen layer has nothing for the part (spec §6.13).

    R1's silkscreen is on the layer and references it; R3's is on the layer without a
    reference (the layer covers it); R2 has nothing on the layer, so its package silkscreen
    is drawn; R4 is on the bottom, which has no silkscreen layer.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.layer("SST", "SILKSCREEN", "TOP")
    two_layers(d, drill=False)
    profile(d, 16, 6)
    bracket = [(-1.3, 0.6), (-1.3, 0.9), (1.3, 0.9), (1.3, 0.6)]
    silk = (
        f'<SilkScreen><Marking markingUsage="NONE"><Polyline>{d.polygon(bracket, close=False)}'
        f'<LineDescRef id="SILK"/></Polyline></Marking></SilkScreen>'
    )
    two_pin_package(d, "R0805", silk)
    features = {"TOP": [], "BOTTOM": []}
    parts = [
        ("R1", "TOP", 3, 3, 0, False),
        ("R2", "TOP", 7, 3, 0, False),
        ("R3", "TOP", 11, 3, 0, False),
        ("R4", "BOTTOM", 14, 3, 0, True),
    ]
    place_two_pin(d, parts, "R0805", features)
    for side, sets in features.items():
        d.step.append(f'<LayerFeature layerRef="{side}">{"".join(sets)}</LayerFeature>')
    at = lambda x: [(x + px, 3 + py) for px, py in bracket]
    d.step.append(
        '<LayerFeature layerRef="SST">'
        f'<Set componentRef="R1">{trace(d, at(3), "SILK")}</Set>'
        f'<Set>{trace(d, at(11), "SILK")}</Set>'
        "</LayerFeature>"
    )
    return d


def panel():
    """A panel: steps placed by StepRepeat, nested, rotated and flipped (spec §6.14).

    Step `board` (20 × 12 mm with a notch, datum in its centre) has a part on each side,
    two nets, traces, vias, a mounting hole, silkscreen with a `Text`, paste and package
    assembly drawings with a `Text` marking. Step `strip` repeats it twice along X in a frame with a local fiducial. Step
    `panel` repeats the strip twice along Y and places two more boards, rotated by 90°, one
    of them flipped (`mirror`), and has rails with global fiducials and tooling holes.
    `Content` lists the board first: the panel converts because no step repeats it.
    """
    d = Doc()
    d.line_desc("TRACE", 0.25)
    d.line_desc("OUTLINE", 0.1)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.primitive("APERTURE", f'<RectCenter width="{d.u(0.8)}" height="{d.u(1.0)}"/>')
    d.primitive("VIA", f'<Circle diameter="{d.u(0.6)}"/>')
    d.primitive("FID", f'<Circle diameter="{d.u(1.0)}"/>')
    d.layer("TOP_SILK", "SILKSCREEN", "TOP")
    d.layer("TOP_PASTE", "SOLDERPASTE", "TOP")
    two_layers(d)
    d.layer("BOT_PASTE", "SOLDERPASTE", "BOTTOM")
    d.layer("BOT_SILK", "SILKSCREEN", "BOTTOM")
    d.step_refs = ["board", "strip", "panel"]

    def contour(outline, cutouts=()):
        holes = "".join(f"<Cutout>{d.rect(*c)}</Cutout>" for c in cutouts)
        return f"<Profile><Polygon>{d.polygon(outline)}</Polygon>{holes}</Profile>"

    def hole(name, x, y, diameter, plating):
        return (
            f'<Hole name="{name}" diameter="{d.u(diameter)}" platingStatus="{plating}" '
            f'plusTol="0" minusTol="0" {d.xy(x, y)}/>'
        )

    def fiducial(element, x, y):
        return f'<{element}><Location {d.xy(x, y)}/><StandardPrimitiveRef id="FID"/></{element}>'

    def silk(points, ref=None):
        component = f' componentRef="{ref}"' if ref else ""
        return f"<Set{component}>{trace(d, points, 'SILK')}</Set>"

    # The board: R1 on top, C1 mirrored on the bottom; nets GND and VCC.
    board = [contour([(0, 0), (20, 0), (20, 9), (17, 9), (17, 12), (0, 12)])]
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.6, 1.0, 0.6)}</Polygon>'
        f'<LineDescRef id="OUTLINE"/></Outline>'
        f'<Marking markingUsage="NONE"><Polyline>{d.polygon([(0.2, 0.3), (0.6, 0.0), (0.2, -0.3)], close=False)}'
        f'<LineDescRef id="OUTLINE"/></Polyline></Marking>'
        f'<Marking markingUsage="PIN_ONE">{text_element(d, "1", (-0.9, -0.35, -0.3, 0.35))}</Marking>'
        "</AssemblyDrawing>"
    )
    main_step, d.step = d.step, board
    two_pin_package(d, "R0805", drawing)
    d.step = main_step
    parts = [("R1", "TOP", 5, 6, 0, False, ("GND", "VCC")), ("C1", "BOTTOM", 15, 6, 0, True, ("VCC", "GND"))]
    copper = {"TOP": [], "BOTTOM": []}
    paste = {"TOP": [], "BOTTOM": []}
    for ref, side, x, y, rot, mirror, nets in parts:
        mirror_attr = ' mirror="true"' if mirror else ""
        xform = f'<Xform rotation="{rot:g}"{mirror_attr}/>' if rot or mirror else ""
        board.append(
            f'<Component refDes="{ref}" packageRef="R0805" layerRef="{side}" part="P" '
            f'mountType="SMT" standoff="0" height="{d.u(0.6)}">{xform}<Location {d.xy(x, y)}/></Component>'
        )
        for (n, px), net in zip((("1", -0.75), ("2", 0.75)), nets):
            qx, qy = placed(x, y, rot, mirror, px, 0)
            copper[side].append(
                f'<Set net="{net}" padUsage="TERMINATION">{pad(d, qx, qy, "PAD", (ref, n))}</Set>'
            )
            paste[side].append(f'<Set>{pad(d, qx, qy, "APERTURE", (ref, n))}</Set>')
    copper["TOP"] += [
        f'<Set net="VCC">{trace(d, [(5.75, 6), (5.75, 9), (10, 9)], "TRACE")}</Set>',
        f'<Set net="GND">{trace(d, [(4.25, 6), (4.25, 2)], "TRACE")}</Set>',
        f'<Set net="GND">{fill(d, 2, 1, 9, 3)}</Set>',
    ]
    copper["BOTTOM"] += [
        f'<Set net="VCC">{trace(d, [(10, 9), (15.75, 9), (15.75, 6)], "TRACE")}</Set>',
        f'<Set net="GND">{trace(d, [(14.25, 6), (14.25, 2), (8, 2)], "TRACE")}</Set>',
    ]
    for side in ("TOP", "BOTTOM"):
        vias = f'<Set net="VCC" padUsage="VIA">{pad(d, 10, 9, "VIA")}</Set>'
        vias += f'<Set net="GND" padUsage="VIA">{pad(d, 8, 2, "VIA")}</Set>'
        board.append(f'<LayerFeature layerRef="{side}">{"".join(copper[side])}{vias}</LayerFeature>')
    board.append(
        '<LayerFeature layerRef="TOP_SILK">'
        + silk([(3.2, 5.0), (6.8, 5.0), (6.8, 7.0), (3.2, 7.0), (3.2, 5.0)], "R1")
        + silk([(1, 10), (3, 10), (1, 11.5), (1, 10)])
        + f"<Set><Features><Location {d.xy(0, 0)}/>{text_element(d, 'REV A', (5, 10, 13, 11.5))}</Features></Set>"
        + "</LayerFeature>"
    )
    board.append(
        '<LayerFeature layerRef="BOT_SILK">'
        + silk([(13.2, 5.0), (16.8, 5.0), (16.8, 7.0), (13.2, 7.0), (13.2, 5.0)], "C1")
        + "</LayerFeature>"
    )
    board.append(f'<LayerFeature layerRef="TOP_PASTE">{"".join(paste["TOP"])}</LayerFeature>')
    board.append(f'<LayerFeature layerRef="BOT_PASTE">{"".join(paste["BOTTOM"])}</LayerFeature>')
    board.append(
        '<LayerFeature layerRef="DRILL">'
        f'<Set net="VCC">{hole("V1", 10, 9, 0.3, "VIA")}</Set>'
        f'<Set net="GND">{hole("V2", 8, 2, 0.3, "VIA")}</Set>'
        f'<Set>{hole("M1", 2.5, 8, 1.2, "NONPLATED")}</Set>'
        "</LayerFeature>"
    )
    d.add_step("board", (10, 6), board)

    # The strip: two boards in windows of a frame, a local fiducial on the bar between them.
    d.add_step(
        "strip",
        (0, 0),
        [
            contour([(0, 0), (52, 0), (52, 18), (0, 18)], [(1, 1, 25, 17), (27, 1, 51, 17)]),
            f'<StepRepeat stepRef="board" {d.xy(13, 9)} nx="2" ny="1" dx="{d.u(26)}" dy="0" angle="0" mirror="false"/>',
            f'<LayerFeature layerRef="TOP"><Set>{fiducial("LocalFiducial", 26, 9)}</Set></LayerFeature>',
        ],
    )

    # The panel: rails around two strips, a rotated board and a flipped one.
    d.step.append(
        contour(
            [(0, 0), (100, 0), (100, 46), (0, 46)],
            [(5, 5, 57, 41), (60, 11, 76, 35), (79, 11, 95, 35)],
        )
    )
    d.step.append(
        f'<StepRepeat stepRef="strip" {d.xy(5, 5)} nx="1" ny="2" dx="0" dy="{d.u(18)}" angle="0" mirror="false"/>'
    )
    d.step.append(
        f'<StepRepeat stepRef="board" {d.xy(68, 23)} nx="1" ny="1" dx="0" dy="0" angle="90" mirror="false"/>'
    )
    d.step.append(
        f'<StepRepeat stepRef="board" {d.xy(87, 23)} nx="1" ny="1" dx="0" dy="0" angle="90" mirror="true"/>'
    )
    rails = {
        "TOP": [("GlobalFiducial", 2.5, 2.5), ("GlobalFiducial", 97.5, 2.5), ("GlobalFiducial", 2.5, 43.5)],
        "BOTTOM": [("GlobalFiducial", 2.5, 2.5), ("GoodPanelMark", 97.5, 43.5)],
    }
    for side, marks in rails.items():
        sets = "".join(fiducial(*m) for m in marks)
        d.step.append(f'<LayerFeature layerRef="{side}"><Set>{sets}</Set></LayerFeature>')
    tooling = "".join(
        hole(f"T{k}", x, y, 2.0, "NONPLATED")
        for k, (x, y) in enumerate([(2.5, 23), (97.5, 23), (50, 2.5)], 1)
    )
    d.step.append(f'<LayerFeature layerRef="DRILL"><Set>{tooling}</Set></LayerFeature>')
    return d


def outline_cutouts():
    """Cut-outs drawn only on a `BOARD_OUTLINE` layer, as KiCad writes them (spec §6.7).

    The profile (30 × 20 mm with rounded corners) has no `Cutout`. Layer `Edge.Cuts` draws the
    profile again and, as separate lines and arcs in no particular order, some of them reversed
    and with ends up to 8 µm apart, a keyhole (KiCad's from Fomu), a round hole (one arc that
    ends where it starts) and a slot (a closed `Polyline`). These three are cut out. An open
    contour, a square across the board edge and the profile itself are not.
    """
    d = Doc()
    d.line_desc("EDGE", 0.05)
    two_layers(d, drill=False)
    d.layer("Edge.Cuts", "BOARD_OUTLINE", "ALL")

    def curve(x, y, cx, cy, clockwise=False):
        return (
            f'<PolyStepCurve {d.xy(x, y)} centerX="{d.u(cx)}" centerY="{d.u(cy)}" '
            f'clockwise="{str(clockwise).lower()}"/>'
        )

    def line(x0, y0, x1, y1):
        return (
            f'<Line startX="{d.u(x0)}" startY="{d.u(y0)}" endX="{d.u(x1)}" endY="{d.u(y1)}">'
            '<LineDescRef id="EDGE"/></Line>'
        )

    def arc(x0, y0, x1, y1, cx, cy, clockwise):
        return (
            f'<Arc startX="{d.u(x0)}" startY="{d.u(y0)}" endX="{d.u(x1)}" endY="{d.u(y1)}" '
            f'centerX="{d.u(cx)}" centerY="{d.u(cy)}" clockwise="{str(clockwise).lower()}">'
            '<LineDescRef id="EDGE"/></Arc>'
        )

    outline = (
        f"<PolyBegin {d.xy(1, 0)}/><PolyStepSegment {d.xy(29, 0)}/>{curve(30, 1, 29, 1)}"
        f"<PolyStepSegment {d.xy(30, 19)}/>{curve(29, 20, 29, 19)}"
        f"<PolyStepSegment {d.xy(1, 20)}/>{curve(0, 19, 1, 19)}"
        f"<PolyStepSegment {d.xy(0, 1)}/>{curve(1, 0, 1, 1)}"
    )
    d.step.append(f"<Profile><Polygon>{outline}</Polygon></Profile>")
    edges = [
        # The profile itself.
        line(1, 0, 29, 0), arc(29, 0, 30, 1, 29, 1, False), line(30, 1, 30, 19),
        arc(30, 19, 29, 20, 29, 19, False), line(29, 20, 1, 20), arc(1, 20, 0, 19, 1, 19, False),
        line(0, 19, 0, 1), arc(0, 1, 1, 0, 1, 1, False),
        # The keyhole around (8, 10): the top arc ends 8 µm short, the line is reversed.
        arc(8.6, 9.15, 7.4, 9.15, 8, 9.15, True),
        arc(7.4, 10.85, 8.592, 10.85, 8, 10.85, True),
        line(8.6, 9.15, 8.6, 10.85),
        arc(7.4, 9.15, 7.4, 10.85, 7.4, 10, True),
        # A round hole: one arc that ends where it starts.
        arc(17.5, 10, 17.5, 10, 16, 10, False),
        # An open contour: three sides of a rectangle.
        line(20, 4, 26, 4), line(26, 4, 26, 7), line(26, 7, 20, 7),
        # A square across the board edge.
        line(27, 8, 32, 8), line(32, 8, 32, 12), line(32, 12, 27, 12), line(27, 12, 27, 8),
    ]
    slot = (
        f"<PolyBegin {d.xy(20, 13.25)}/><PolyStepSegment {d.xy(25, 13.25)}/>"
        f"{curve(25, 14.75, 25, 14)}<PolyStepSegment {d.xy(20, 14.75)}/>{curve(20, 13.25, 20, 14)}"
    )
    d.step.append(
        '<LayerFeature layerRef="Edge.Cuts">'
        f'<Set><Features><UserSpecial>{"".join(edges)}</UserSpecial></Features></Set>'
        f'<Set><Features><Location x="0" y="0"/><Polyline>{slot}<LineDescRef id="EDGE"/></Polyline></Features></Set>'
        "</LayerFeature>"
    )
    return d


def pinless_package():
    """Components without pads get no placeholder body unless they give a height (spec §6.8).

    No package gives a height, as in KiCad's files. R1 (`SMT`, with pads) gets a body half its
    outline's smaller side high. LOGO1 (a package without pins whose `pinOne` is `UNKNOWN`, as
    KiCad writes logos) and H1 (a mounting hole: one pin that no pad references) get none, and
    the logo's `pinOne` is not reported. LOGO2, the same logo with a component `height`, gets a
    body.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.0)}"/>')
    d.primitive("HOLE", f'<Circle diameter="{d.u(3.2)}"/>')
    two_layers(d)
    profile(d, 25, 15)
    d.step.append(
        '<Package name="R0603" type="RESISTOR" pinOne="1">'
        f'<Outline><Polygon>{d.rect(-1.2, -0.6, 1.2, 0.6)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(-0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        f'<Pin number="2"><Location {d.xy(0.8, 0)}/><StandardPrimitiveRef id="PAD"/></Pin>'
        "</Package>"
    )
    d.step.append(
        '<Package name="LOGO" type="OTHER" pinOne="UNKNOWN">'
        f'<Outline><Polygon>{d.rect(-2, -1, 2, 1)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        "</Package>"
    )
    d.step.append(
        '<Package name="MountingHole_3.2mm" type="OTHER" pinOne="1">'
        f'<Outline><Polygon>{d.rect(-1.8, -1.8, 1.8, 1.8)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
        f'<Pin number="1"><Location {d.xy(0, 0)}/><StandardPrimitiveRef id="HOLE"/></Pin>'
        "</Package>"
    )
    for ref, package, mount, x, y, height in [
        ("R1", "R0603", "SMT", 5, 7.5, None),
        ("LOGO1", "LOGO", "SMT", 12, 10, None),
        ("LOGO2", "LOGO", "SMT", 12, 5, 0.3),
        ("H1", "MountingHole_3.2mm", "THMT", 20, 7.5, None),
    ]:
        height = f' height="{d.u(height)}"' if height else ""
        d.step.append(
            f'<Component refDes="{ref}" packageRef="{package}" layerRef="TOP" '
            f'mountType="{mount}"{height}><Location {d.xy(x, y)}/></Component>'
        )
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="N1" padUsage="TERMINATION">{pad(d, 4.2, 7.5, "PAD", ("R1", "1"))}</Set>'
        f'<Set net="N2" padUsage="TERMINATION">{pad(d, 5.8, 7.5, "PAD", ("R1", "2"))}</Set>'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set>'
        f'<Hole name="H1" diameter="{d.u(3.2)}" platingStatus="NONPLATED" plusTol="0" minusTol="0" {d.xy(20, 7.5)}/>'
        "</Set></LayerFeature>"
    )
    return d


def board_sized_package():
    """A placeholder body covering more than half of its board is left out (spec §6.8).

    U1's footprint is the board itself, as for a carrier board made to drop in for a module
    (MIAO's XIAO footprint): its outline covers the 20 × 16 mm board and its pads ring the
    edge. It gets no body but stays a component. U2, a module covering a fifth of the board,
    and R1 get bodies, and so does U3, a board-sized shield whose height the file gives.
    """
    d = Doc()
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PAD", f'<RectCenter width="{d.u(1.0)}" height="{d.u(1.0)}"/>')
    two_layers(d, drill=False)
    profile(d, 20, 16)
    packages = {
        "MODULE_BOARD": ((-10, -8, 10, 8), [(-9, -7), (9, -7), (9, 7), (-9, 7)]),
        "MODULE_8X8": ((-4, -4, 4, 4), [(-3, -3), (3, -3), (3, 3), (-3, 3)]),
        "R0603": ((-1.2, -0.6, 1.2, 0.6), [(-0.8, 0), (0.8, 0)]),
        "SHIELD_BOARD": ((-10, -8, 10, 8), [(-9, 0), (9, 0)]),
    }
    for name, (box, pins) in packages.items():
        pin_xml = "".join(
            f'<Pin number="{n}"><Location {d.xy(x, y)}/><StandardPrimitiveRef id="PAD"/></Pin>'
            for n, (x, y) in enumerate(pins, 1)
        )
        d.step.append(
            f'<Package name="{name}" type="OTHER" pinOne="1">'
            f'<Outline><Polygon>{d.rect(*box)}</Polygon><LineDescRef id="OUTLINE"/></Outline>'
            f"{pin_xml}</Package>"
        )
    pads = []
    parts = [
        ("U1", "MODULE_BOARD", 10, 8, ""),
        ("U2", "MODULE_8X8", 7, 8, ""),
        ("R1", "R0603", 15, 8, ""),
        ("U3", "SHIELD_BOARD", 10, 8, f' height="{d.u(1.5)}"'),
    ]
    for ref, package, x, y, height in parts:
        d.step.append(
            f'<Component refDes="{ref}" packageRef="{package}" layerRef="TOP" mountType="SMT"{height}>'
            f"<Location {d.xy(x, y)}/></Component>"
        )
        for n, (px, py) in enumerate(packages[package][1], 1):
            pads.append(f'<Set padUsage="TERMINATION">{pad(d, x + px, y + py, "PAD", (ref, str(n)))}</Set>')
    d.step.append(f'<LayerFeature layerRef="TOP">{"".join(pads)}</LayerFeature>')
    return d


def text_element(d, string, box, font=None, xform="", color=""):
    """A `Text` in `box` (x0, y0, x1, y1); non-ASCII characters as character references."""
    x0, y0, x1, y1 = box
    string = escape(string, {'"': "&quot;"}).encode("ascii", "xmlcharrefreplace").decode()
    font_ref = f'<FontRef id="{font}"/>' if font else ""
    return (
        f'<Text textString="{string}" fontSize="{max(1, round(y1 - y0))}">{xform}'
        f'<BoundingBox lowerLeftX="{d.u(x0)}" lowerLeftY="{d.u(y0)}" '
        f'upperRightX="{d.u(x1)}" upperRightY="{d.u(y1)}"/>{font_ref}{color}</Text>'
    )


def text():
    """`Text` in an embedded font, in the bundled font for an external font and without one,
    rotated, mirrored, too wide for its box, with Latin-1 and unknown characters, on
    copper: cut by a hole, and knocked out of a plane, and in a package's assembly drawing,
    placed with its rotated part on `@assembly-top` (spec §6.6, §6.13, §8.2)."""
    d = Doc()
    d.line_desc("UNDERLINE", 0.3)
    d.line_desc("OUTLINE", 0.1)
    d.primitive("PAD", f'<RectCenter width="{d.u(0.9)}" height="{d.u(1.2)}"/>')
    d.layer("TOP", "CONDUCTOR", "TOP")
    d.layer("BOTTOM", "CONDUCTOR", "BOTTOM")
    d.layer("DRILL", "DRILL", "ALL", span=("TOP", "BOTTOM"))
    d.layer("SILK", "SILKSCREEN", "TOP")
    profile(d, 50, 34)

    # A plotter font in a 1 mm design: capitals 1 high on the baseline, descenders to -0.2.
    stroke = f'<LineDesc lineWidth="{d.u(0.12)}" lineEnd="ROUND"/>'

    def path(points):
        """A path from points and (x, y, centerX, centerY) clockwise arcs."""
        (x0, y0), rest = points[0], points[1:]
        steps = "".join(
            f"<PolyStepSegment {d.xy(*p)}/>"
            if len(p) == 2
            else f'<PolyStepCurve {d.xy(*p[:2])} centerX="{d.u(p[2])}" '
            f'centerY="{d.u(p[3])}" clockwise="true"/>'
            for p in rest
        )
        return f"<Polyline><PolyBegin {d.xy(x0, y0)}/>{steps}{stroke}</Polyline>"

    def line(x0, y0, x1, y1):
        return (
            f'<Line startX="{d.u(x0)}" startY="{d.u(y0)}" endX="{d.u(x1)}" endY="{d.u(y1)}">'
            f"{stroke}</Line>"
        )

    def glyph(code, width, *shapes):
        return (
            f'<Glyph charCode="{code}" lowerLeftX="0" lowerLeftY="{d.u(-0.2)}" '
            f'upperRightX="{d.u(width)}" upperRightY="{d.u(1)}">{"".join(shapes)}</Glyph>'
        )

    o = path([(0.15, 0.3), (0.15, 0.7), (0.65, 0.7, 0.4, 0.7), (0.65, 0.3), (0.15, 0.3, 0.4, 0.3)])
    glyphs = [
        glyph("20", 0.5),
        glyph(
            "41",
            0.8,
            path([(0.05, 0), (0.4, 1), (0.75, 0)]),
            line(0.17, 0.35, 0.63, 0.35),
        ),
        glyph(
            "42",
            0.8,
            path([(0.1, 0), (0.1, 1), (0.42, 1), (0.42, 0.5, 0.42, 0.75), (0.1, 0.5)]),
            path([(0.1, 0.5), (0.47, 0.5), (0.47, 0, 0.47, 0.25), (0.1, 0)]),
        ),
        glyph("44", 0.8, path([(0.1, 0), (0.1, 1), (0.25, 1), (0.25, 0, 0.25, 0.5), (0.1, 0)])),
        glyph("4F", 0.8, o),
        glyph(
            "52",
            0.8,
            path([(0.1, 0), (0.1, 1), (0.42, 1), (0.42, 0.5, 0.42, 0.75), (0.1, 0.5)]),
            line(0.35, 0.5, 0.65, 0),
        ),
        # Ø, with a four-digit charCode.
        glyph("00D8", 0.8, o, line(0.1, -0.05, 0.7, 1.05)),
    ]
    d.font(
        "PLOTTER",
        f'<FontDefEmbedded name="plotter">{stroke}{"".join(glyphs)}</FontDefEmbedded>',
    )
    d.font("ARIAL", '<FontDefExternal name="Arial" urn="urn:example:font:arial"/>')

    # A part whose assembly drawing has its reference designator as a Text marking.
    refdes = text_element(d, "U1", (-0.5, -0.3, 0.5, 0.3))
    drawing = (
        f'<AssemblyDrawing><Outline><Polygon>{d.rect(-1.0, -0.6, 1.0, 0.6)}</Polygon>'
        f'<LineDescRef id="OUTLINE"/></Outline>'
        f'<Marking markingUsage="REFDES">{refdes}</Marking></AssemblyDrawing>'
    )
    two_pin_package(d, "U0805", drawing)
    pads = {"TOP": []}
    place_two_pin(d, [("U1", "TOP", 44, 7, 90, False)], "U0805", pads)

    def features(inner, x=0, y=0):
        return f"<Features><Location {d.xy(x, y)}/>{inner}</Features>"

    silk = [
        # Embedded glyphs; `2` is not in the font and comes from the bundled one.
        text_element(d, "BOARD Ø2", (2, 28.5, 32, 32.5), font="PLOTTER"),
        # An external font is drawn with the bundled font.
        text_element(
            d, "External font: Arial", (2, 24, 40, 27), font="ARIAL",
            color='<ColorTerm name="WHITE"/>',
        ),
        # Latin-1 in the bundled font; Ω has no glyph and is drawn as a box.
        text_element(d, "Ærøskøbing µ±0.1° Ω", (2, 19, 42, 22)),
        # Wider than its box: scaled down to fit.
        text_element(d, "Too wide for its box", (18, 14.5, 38, 17)),
    ]
    mirrored = text_element(d, "Mirror", (0, 0, 12, 2.5), xform='<Xform mirror="true"/>')
    rotated = text_element(
        d, "R90", (0, 0, 14, 2.5),
        xform=f'<Xform xOffset="{d.u(47)}" yOffset="{d.u(14)}" rotation="90"/>',
    )
    d.step.append(
        '<LayerFeature layerRef="SILK">'
        + "".join(f"<Set>{features(t)}</Set>" for t in silk)
        + f"<Set>{features(mirrored, 14, 14.5)}</Set>"
        + f"<Set>{features(rotated)}</Set>"
        + "</LayerFeature>"
    )
    # Copper text with an underline in one feature, cut by a hole through the stem of the N,
    # and text knocked out of a plane.
    underline = (
        f'<Line startX="{d.u(2)}" startY="{d.u(3.3)}" endX="{d.u(9.5)}" endY="{d.u(3.3)}">'
        '<LineDescRef id="UNDERLINE"/></Line>'
    )
    gnd = text_element(d, "GND", (2, 3, 14, 6))
    knockout = text_element(d, "CUT", (22, 3.5, 36, 6.5))
    d.step.append(
        '<LayerFeature layerRef="TOP">'
        f'<Set net="GND">{features(f"<UserSpecial>{gnd}{underline}</UserSpecial>")}</Set>'
        f'<Set net="GND">{fill(d, 20, 2, 38, 8)}</Set>'
        f'<Set polarity="NEGATIVE">{features(knockout)}</Set>'
        f'{"".join(pads["TOP"])}'
        "</LayerFeature>"
    )
    d.step.append(
        '<LayerFeature layerRef="DRILL"><Set>'
        f'<Hole name="H1" diameter="{d.u(0.6)}" platingStatus="NONPLATED" plusTol="0" '
        f'minusTol="0" {d.xy(4.79, 4.9)}/>'
        "</Set></LayerFeature>"
    )
    return d


def box_model():
    """A 1.6 × 0.8 × 0.5 mm box as a .gltf with an embedded buffer, in metres."""
    (x, z, h) = (0.8e-3, 0.4e-3, 0.5e-3)
    corners = [(sx * x, y, sz * z) for y in (0.0, h) for sz in (-1, 1) for sx in (-1, 1)]
    # Faces as quads of corner indices, counter-clockwise from outside.
    quads = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    indices = [i for a, b, c, e in quads for i in (a, b, c, a, c, e)]
    data = b"".join(struct.pack("<3f", *c) for c in corners)
    data += b"".join(struct.pack("<H", i) for i in indices)
    uri = "data:application/octet-stream;base64," + base64.b64encode(data).decode()
    gltf = {
        "asset": {"version": "2.0", "generator": "boardui samples"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "box", "mesh": 0}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1, "material": 0}]}],
        "materials": [
            {"name": "ceramic", "pbrMetallicRoughness": {"baseColorFactor": [0.55, 0.45, 0.3, 1], "metallicFactor": 0}}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 8, "type": "VEC3",
             "min": [-x, 0, -z], "max": [x, h, z]},
            {"bufferView": 1, "componentType": 5123, "count": len(indices), "type": "SCALAR"},
        ],
        "bufferViews": [
            {"buffer": 0, "byteLength": 96, "target": 34962},
            {"buffer": 0, "byteOffset": 96, "byteLength": 2 * len(indices), "target": 34963},
        ],
        "buffers": [{"byteLength": len(data), "uri": uri}],
    }
    return json.dumps(gltf, indent=1) + "\n"


def colours():
    """Soldermask and silkscreen colours from specs and the colour dictionary (spec §6.10)."""
    d = Doc()
    d.line_desc("TRACE", 0.3)
    d.line_desc("SILK", 0.15)
    d.primitive("PAD", f'<RectCenter width="{d.u(1.2)}" height="{d.u(1.4)}"/>')
    d.color("MASK_RGB", 90, 30, 120)
    d.color("COPPER_RGB", 255, 0, 0)
    # Top mask: an explicit colour wins over a colour name in the same spec.
    d.spec(
        "MASK_TOP",
        '<General type="MATERIAL"><Property text="Color : Red"/><ColorRef id="MASK_RGB"/></General>',
    )
    # Top silkscreen: a standard ColorTerm.
    d.spec("SILK_TOP", '<General type="MATERIAL"><ColorTerm name="YELLOW"/></General>')
    # Copper keeps its default even with a colour.
    d.spec("COPPER", '<General type="MATERIAL"><ColorRef id="COPPER_RGB"/></General>')
    # Bottom mask as KiCad 9 writes it: the stack-up refers to `SPEC_SMB`, the spec is `SMB_2`.
    d.spec(
        "SMB_2",
        '<General type="MATERIAL"><Property text="SOLDERMASK"/>'
        '<Property text="Color : Matte Black"/><Property text="Type : Bottom Solder Mask"/></General>',
    )
    # Bottom silkscreen: a name that maps to the default colour.
    d.spec("SILK_BOTTOM", '<General type="MATERIAL"><Property text="Color : White"/></General>')
    d.layer("SST", "SILKSCREEN", "TOP", specs=["SILK_TOP"])
    d.layer("SMT", "SOLDERMASK", "TOP", specs=["MASK_TOP"])
    d.layer("TOP", "CONDUCTOR", "TOP", specs=["COPPER"])
    d.layer("CORE", "DIELCORE", "INTERNAL")
    d.layer("BOTTOM", "CONDUCTOR", "BOTTOM")
    d.layer("SMB", "SOLDERMASK", "BOTTOM")
    d.layer("SSB", "SILKSCREEN", "BOTTOM", specs=["SILK_BOTTOM"])
    stack = [("SST", 0.01), ("SMT", 0.02), ("TOP", 0.035), ("CORE", 1.51)]
    stack += [("BOTTOM", 0.035), ("SMB", 0.02), ("SSB", 0.01)]
    rows = "".join(
        f'<StackupLayer layerOrGroupRef="{name}" thickness="{d.u(t)}" tolPlus="0" tolMinus="0"'
        f' sequence="{i}"' + ('><SpecRef id="SPEC_SMB"/></StackupLayer>' if name == "SMB" else "/>")
        for i, (name, t) in enumerate(stack)
    )
    d.layers.append(
        f'<Stackup name="S" overallThickness="{d.u(1.64)}" tolPlus="0" tolMinus="0" whereMeasured="MASK">'
        f'<StackupGroup name="G" thickness="{d.u(1.64)}" tolPlus="0" tolMinus="0">{rows}</StackupGroup></Stackup>'
    )
    profile(d, 10, 6)
    pads = "".join(pad(d, x, 3, "PAD") for x in (3, 7))
    outline = trace(d, [(1, 1), (9, 1), (9, 5), (1, 5), (1, 1)], "SILK")
    d.step += [
        # Cadence writes the CAD tool's display colour on a layer's first `Set`: not used.
        f'<LayerFeature layerRef="TOP"><Set><ColorRef id="COPPER_RGB"/></Set>'
        f'<Set net="N">{pads}{trace(d, [(3, 3), (7, 3)], "TRACE")}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SMT"><Set>{pads}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SST"><Set>{outline}</Set></LayerFeature>',
        f'<LayerFeature layerRef="BOTTOM"><Set net="N">{fill(d, 2, 2, 8, 4)}</Set></LayerFeature>',
        f'<LayerFeature layerRef="SSB"><Set>{outline}</Set></LayerFeature>',
    ]
    return d


def main():
    samples = {
        "minimal-2layer": minimal("MILLIMETER"),
        "units-inch": minimal("INCH"),
        "units-micron": minimal("MICRON"),
        "overlap-priority": overlap_priority(),
        "negative-polarity": negative_polarity(),
        "zero-width-lines": zero_width_lines(),
        "fiducials": fiducials(),
        "hexagon-moire": hexagon_moire(),
        "primitive-xform": primitive_xform(),
        "hatch-fill": hatch_fill(),
        "line-styles": line_styles(),
        "slots": slots(),
        "pad-stacks": pad_stacks(),
        "pad-stacks-drill-layer": pad_stacks_drill_layer(),
        "conductor-core": conductor_core(),
        "bottom-placement": bottom_placement(),
        "paste-layer": paste_layer(),
        "drawing-layers": drawing_layers(),
        "assembly-drawing": assembly_drawing(),
        "package-silkscreen": package_silkscreen(),
        "user-models": minimal("MILLIMETER"),
        "colours": colours(),
        "panel": panel(),
        "text": text(),
        "outline-cutouts": outline_cutouts(),
        "pinless-package": pinless_package(),
        "board-sized-package": board_sized_package(),
    }
    for name, d in samples.items():
        d.write(HERE / name / f"{name}.xml", name, "panel" if name == "panel" else "board")
    models = HERE / "user-models"
    (models / "r0603.gltf").write_text(box_model())
    mapping = {
        "version": 1,
        "models": [{"match": {"package": "R0603"}, "file": "r0603.gltf"}],
    }
    (models / "models.json").write_text(json.dumps(mapping, indent=2) + "\n")


if __name__ == "__main__":
    main()
